-- ============================================================
-- Fake Data Generator – Seed / Lookup Data
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- EN-US  Male first names (150)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','first_male','James'),('en-US','first_male','John'),('en-US','first_male','Robert'),
('en-US','first_male','Michael'),('en-US','first_male','William'),('en-US','first_male','David'),
('en-US','first_male','Richard'),('en-US','first_male','Joseph'),('en-US','first_male','Thomas'),
('en-US','first_male','Charles'),('en-US','first_male','Christopher'),('en-US','first_male','Daniel'),
('en-US','first_male','Matthew'),('en-US','first_male','Anthony'),('en-US','first_male','Mark'),
('en-US','first_male','Donald'),('en-US','first_male','Steven'),('en-US','first_male','Paul'),
('en-US','first_male','Andrew'),('en-US','first_male','Joshua'),('en-US','first_male','Kenneth'),
('en-US','first_male','Kevin'),('en-US','first_male','Brian'),('en-US','first_male','George'),
('en-US','first_male','Timothy'),('en-US','first_male','Ronald'),('en-US','first_male','Edward'),
('en-US','first_male','Jason'),('en-US','first_male','Jeffrey'),('en-US','first_male','Ryan'),
('en-US','first_male','Jacob'),('en-US','first_male','Gary'),('en-US','first_male','Nicholas'),
('en-US','first_male','Eric'),('en-US','first_male','Jonathan'),('en-US','first_male','Stephen'),
('en-US','first_male','Larry'),('en-US','first_male','Justin'),('en-US','first_male','Scott'),
('en-US','first_male','Brandon'),('en-US','first_male','Benjamin'),('en-US','first_male','Samuel'),
('en-US','first_male','Raymond'),('en-US','first_male','Gregory'),('en-US','first_male','Frank'),
('en-US','first_male','Alexander'),('en-US','first_male','Patrick'),('en-US','first_male','Jack'),
('en-US','first_male','Dennis'),('en-US','first_male','Jerry'),('en-US','first_male','Tyler'),
('en-US','first_male','Aaron'),('en-US','first_male','Jose'),('en-US','first_male','Adam'),
('en-US','first_male','Henry'),('en-US','first_male','Nathan'),('en-US','first_male','Douglas'),
('en-US','first_male','Zachary'),('en-US','first_male','Peter'),('en-US','first_male','Kyle'),
('en-US','first_male','Ethan'),('en-US','first_male','Walter'),('en-US','first_male','Noah'),
('en-US','first_male','Jeremy'),('en-US','first_male','Christian'),('en-US','first_male','Keith'),
('en-US','first_male','Roger'),('en-US','first_male','Terry'),('en-US','first_male','Gerald'),
('en-US','first_male','Harold'),('en-US','first_male','Sean'),('en-US','first_male','Austin'),
('en-US','first_male','Carl'),('en-US','first_male','Arthur'),('en-US','first_male','Lawrence'),
('en-US','first_male','Dylan'),('en-US','first_male','Jesse'),('en-US','first_male','Jordan'),
('en-US','first_male','Bryan'),('en-US','first_male','Billy'),('en-US','first_male','Joe'),
('en-US','first_male','Bruce'),('en-US','first_male','Gabriel'),('en-US','first_male','Logan'),
('en-US','first_male','Albert'),('en-US','first_male','Willie'),('en-US','first_male','Alan'),
('en-US','first_male','Juan'),('en-US','first_male','Wayne'),('en-US','first_male','Elijah'),
('en-US','first_male','Randy'),('en-US','first_male','Roy'),('en-US','first_male','Vincent'),
('en-US','first_male','Ralph'),('en-US','first_male','Eugene'),('en-US','first_male','Russell'),
('en-US','first_male','Bobby'),('en-US','first_male','Mason'),('en-US','first_male','Philip'),
('en-US','first_male','Louis'),('en-US','first_male','Johnny'),('en-US','first_male','Lucas'),
('en-US','first_male','Louis'),('en-US','first_male','Harry'),('en-US','first_male','Wayne'),
('en-US','first_male','Liam'),('en-US','first_male','Oliver'),('en-US','first_male','Aiden'),
('en-US','first_male','Owen'),('en-US','first_male','Caleb'),('en-US','first_male','Miles'),
('en-US','first_male','Hunter'),('en-US','first_male','Wyatt'),('en-US','first_male','Evan'),
('en-US','first_male','Cole'),('en-US','first_male','Brayden'),('en-US','first_male','Jace'),
('en-US','first_male','Connor'),('en-US','first_male','Carson'),('en-US','first_male','Easton'),
('en-US','first_male','Nolan'),('en-US','first_male','Cameron'),('en-US','first_male','Blake'),
('en-US','first_male','Lincoln'),('en-US','first_male','Eli'),('en-US','first_male','Xavier'),
('en-US','first_male','Gavin'),('en-US','first_male','Ian'),('en-US','first_male','Levi'),
('en-US','first_male','Bryson'),('en-US','first_male','Micah'),('en-US','first_male','Grayson'),
('en-US','first_male','Sawyer'),('en-US','first_male','Hudson'),('en-US','first_male','Asher'),
('en-US','first_male','Charlie'),('en-US','first_male','Jaxon'),('en-US','first_male','Dominic'),
('en-US','first_male','Josiah'),('en-US','first_male','Sebastian'),('en-US','first_male','Axel'),
('en-US','first_male','Beau'),('en-US','first_male','Drew'),('en-US','first_male','Declan'),
('en-US','first_male','Elliot'),('en-US','first_male','Felix'),('en-US','first_male','Grant'),
('en-US','first_male','Rowan'),('en-US','first_male','Theodore'),('en-US','first_male','Tobias');

-- ────────────────────────────────────────────────────────────
-- EN-US  Female first names (150)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','first_female','Mary'),('en-US','first_female','Patricia'),('en-US','first_female','Jennifer'),
('en-US','first_female','Linda'),('en-US','first_female','Barbara'),('en-US','first_female','Elizabeth'),
('en-US','first_female','Susan'),('en-US','first_female','Jessica'),('en-US','first_female','Sarah'),
('en-US','first_female','Karen'),('en-US','first_female','Lisa'),('en-US','first_female','Nancy'),
('en-US','first_female','Betty'),('en-US','first_female','Margaret'),('en-US','first_female','Sandra'),
('en-US','first_female','Ashley'),('en-US','first_female','Dorothy'),('en-US','first_female','Kimberly'),
('en-US','first_female','Emily'),('en-US','first_female','Donna'),('en-US','first_female','Michelle'),
('en-US','first_female','Carol'),('en-US','first_female','Amanda'),('en-US','first_female','Melissa'),
('en-US','first_female','Deborah'),('en-US','first_female','Stephanie'),('en-US','first_female','Rebecca'),
('en-US','first_female','Sharon'),('en-US','first_female','Laura'),('en-US','first_female','Cynthia'),
('en-US','first_female','Kathleen'),('en-US','first_female','Amy'),('en-US','first_female','Angela'),
('en-US','first_female','Shirley'),('en-US','first_female','Anna'),('en-US','first_female','Brenda'),
('en-US','first_female','Pamela'),('en-US','first_female','Emma'),('en-US','first_female','Nicole'),
('en-US','first_female','Helen'),('en-US','first_female','Samantha'),('en-US','first_female','Katherine'),
('en-US','first_female','Christine'),('en-US','first_female','Debra'),('en-US','first_female','Rachel'),
('en-US','first_female','Carolyn'),('en-US','first_female','Janet'),('en-US','first_female','Catherine'),
('en-US','first_female','Maria'),('en-US','first_female','Heather'),('en-US','first_female','Diane'),
('en-US','first_female','Julie'),('en-US','first_female','Joyce'),('en-US','first_female','Victoria'),
('en-US','first_female','Kelly'),('en-US','first_female','Christina'),('en-US','first_female','Joan'),
('en-US','first_female','Evelyn'),('en-US','first_female','Lauren'),('en-US','first_female','Judith'),
('en-US','first_female','Olivia'),('en-US','first_female','Frances'),('en-US','first_female','Martha'),
('en-US','first_female','Cheryl'),('en-US','first_female','Megan'),('en-US','first_female','Andrea'),
('en-US','first_female','Ann'),('en-US','first_female','Alice'),('en-US','first_female','Jean'),
('en-US','first_female','Jacqueline'),('en-US','first_female','Hannah'),('en-US','first_female','Doris'),
('en-US','first_female','Kathryn'),('en-US','first_female','Gloria'),('en-US','first_female','Teresa'),
('en-US','first_female','Sara'),('en-US','first_female','Janice'),('en-US','first_female','Rose'),
('en-US','first_female','Julia'),('en-US','first_female','Grace'),('en-US','first_female','Judy'),
('en-US','first_female','Theresa'),('en-US','first_female','Madison'),('en-US','first_female','Beverly'),
('en-US','first_female','Denise'),('en-US','first_female','Marilyn'),('en-US','first_female','Amber'),
('en-US','first_female','Danielle'),('en-US','first_female','Abigail'),('en-US','first_female','Brittany'),
('en-US','first_female','Virginia'),('en-US','first_female','Diana'),('en-US','first_female','Sophia'),
('en-US','first_female','Charlotte'),('en-US','first_female','Natalie'),('en-US','first_female','Isabella'),
('en-US','first_female','Alexis'),('en-US','first_female','Tiffany'),('en-US','first_female','Kayla'),
('en-US','first_female','Ava'),('en-US','first_female','Vanessa'),('en-US','first_female','Mia'),
('en-US','first_female','Natasha'),('en-US','first_female','Chloe'),('en-US','first_female','Zoe'),
('en-US','first_female','Lily'),('en-US','first_female','Ella'),('en-US','first_female','Nora'),
('en-US','first_female','Harper'),('en-US','first_female','Luna'),('en-US','first_female','Aria'),
('en-US','first_female','Scarlett'),('en-US','first_female','Penelope'),('en-US','first_female','Layla'),
('en-US','first_female','Ellie'),('en-US','first_female','Violet'),('en-US','first_female','Aurora'),
('en-US','first_female','Hazel'),('en-US','first_female','Stella'),('en-US','first_female','Claire'),
('en-US','first_female','Audrey'),('en-US','first_female','Savannah'),('en-US','first_female','Brooklyn'),
('en-US','first_female','Leah'),('en-US','first_female','Zoey'),('en-US','first_female','Paisley'),
('en-US','first_female','Addison'),('en-US','first_female','Elena'),('en-US','first_female','Camila'),
('en-US','first_female','Autumn'),('en-US','first_female','Piper'),('en-US','first_female','Willow'),
('en-US','first_female','Skylar'),('en-US','first_female','Naomi'),('en-US','first_female','Delilah'),
('en-US','first_female','Riley'),('en-US','first_female','Lila'),('en-US','first_female','Eva'),
('en-US','first_female','Madeline'),('en-US','first_female','Isabelle'),('en-US','first_female','Maya'),
('en-US','first_female','Serenity'),('en-US','first_female','Kennedy'),('en-US','first_female','Lydia');

-- ────────────────────────────────────────────────────────────
-- EN-US  Middle names (100 each gender, shared from first lists)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','middle_male','Lee'),('en-US','middle_male','Ray'),('en-US','middle_male','Allen'),
('en-US','middle_male','Wayne'),('en-US','middle_male','Dale'),('en-US','middle_male','Dean'),
('en-US','middle_male','Lynn'),('en-US','middle_male','Kent'),('en-US','middle_male','Scott'),
('en-US','middle_male','Jay'),('en-US','middle_male','Alan'),('en-US','middle_male','Earl'),
('en-US','middle_male','Eugene'),('en-US','middle_male','Glen'),('en-US','middle_male','Bruce'),
('en-US','middle_male','Cole'),('en-US','middle_male','Craig'),('en-US','middle_male','Todd'),
('en-US','middle_male','Neil'),('en-US','middle_male','Drew'),('en-US','middle_male','Shane'),
('en-US','middle_male','Blake'),('en-US','middle_male','Brett'),('en-US','middle_male','Chase'),
('en-US','middle_male','Clark'),('en-US','middle_male','Clyde'),('en-US','middle_male','Donald'),
('en-US','middle_male','Douglas'),('en-US','middle_male','Floyd'),('en-US','middle_male','Francis'),
('en-US','middle_male','Grant'),('en-US','middle_male','Harold'),('en-US','middle_male','Howard'),
('en-US','middle_male','Hugh'),('en-US','middle_male','Irving'),('en-US','middle_male','Keith'),
('en-US','middle_male','Lester'),('en-US','middle_male','Lloyd'),('en-US','middle_male','Lyle'),
('en-US','middle_male','Marshall'),('en-US','middle_male','Max'),('en-US','middle_male','Miles'),
('en-US','middle_male','Morris'),('en-US','middle_male','Norman'),('en-US','middle_male','Oliver'),
('en-US','middle_male','Owen'),('en-US','middle_male','Perry'),('en-US','middle_male','Preston'),
('en-US','middle_male','Quinn'),('en-US','middle_male','Reed'),('en-US','middle_male','Reid'),
('en-US','middle_male','Rex'),('en-US','middle_male','Roy'),('en-US','middle_male','Russell'),
('en-US','middle_male','Seth'),('en-US','middle_male','Spencer'),('en-US','middle_male','Stanley'),
('en-US','middle_male','Stuart'),('en-US','middle_male','Travis'),('en-US','middle_male','Troy'),
('en-US','middle_male','Tucker'),('en-US','middle_male','Vernon'),('en-US','middle_male','Victor'),
('en-US','middle_male','Wade'),('en-US','middle_male','Ward'),('en-US','middle_male','Wesley'),
('en-US','middle_male','Wilbur'),('en-US','middle_male','Willis'),('en-US','middle_male','Wilson');

INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','middle_female','Marie'),('en-US','middle_female','Lynn'),('en-US','middle_female','Ann'),
('en-US','middle_female','Grace'),('en-US','middle_female','Mae'),('en-US','middle_female','Rose'),
('en-US','middle_female','Jane'),('en-US','middle_female','Lee'),('en-US','middle_female','Kay'),
('en-US','middle_female','Beth'),('en-US','middle_female','Jean'),('en-US','middle_female','Faye'),
('en-US','middle_female','Claire'),('en-US','middle_female','Faith'),('en-US','middle_female','Hope'),
('en-US','middle_female','Joy'),('en-US','middle_female','Kate'),('en-US','middle_female','Leigh'),
('en-US','middle_female','Rae'),('en-US','middle_female','Ruth'),('en-US','middle_female','Sue'),
('en-US','middle_female','Dawn'),('en-US','middle_female','Elaine'),('en-US','middle_female','Eve'),
('en-US','middle_female','Iris'),('en-US','middle_female','Joan'),('en-US','middle_female','Jolene'),
('en-US','middle_female','June'),('en-US','middle_female','Kate'),('en-US','middle_female','Lois'),
('en-US','middle_female','Louise'),('en-US','middle_female','Mae'),('en-US','middle_female','May'),
('en-US','middle_female','Pearl'),('en-US','middle_female','Paige'),('en-US','middle_female','Quinn'),
('en-US','middle_female','Renee'),('en-US','middle_female','Skye'),('en-US','middle_female','Simone');

-- ────────────────────────────────────────────────────────────
-- EN-US  Last names (500)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','last','Smith'),('en-US','last','Johnson'),('en-US','last','Williams'),
('en-US','last','Brown'),('en-US','last','Jones'),('en-US','last','Garcia'),
('en-US','last','Miller'),('en-US','last','Davis'),('en-US','last','Rodriguez'),
('en-US','last','Martinez'),('en-US','last','Hernandez'),('en-US','last','Lopez'),
('en-US','last','Gonzalez'),('en-US','last','Wilson'),('en-US','last','Anderson'),
('en-US','last','Thomas'),('en-US','last','Taylor'),('en-US','last','Moore'),
('en-US','last','Jackson'),('en-US','last','Martin'),('en-US','last','Lee'),
('en-US','last','Perez'),('en-US','last','Thompson'),('en-US','last','White'),
('en-US','last','Harris'),('en-US','last','Sanchez'),('en-US','last','Clark'),
('en-US','last','Ramirez'),('en-US','last','Lewis'),('en-US','last','Robinson'),
('en-US','last','Walker'),('en-US','last','Young'),('en-US','last','Allen'),
('en-US','last','King'),('en-US','last','Wright'),('en-US','last','Scott'),
('en-US','last','Torres'),('en-US','last','Nguyen'),('en-US','last','Hill'),
('en-US','last','Flores'),('en-US','last','Green'),('en-US','last','Adams'),
('en-US','last','Nelson'),('en-US','last','Baker'),('en-US','last','Hall'),
('en-US','last','Rivera'),('en-US','last','Campbell'),('en-US','last','Mitchell'),
('en-US','last','Carter'),('en-US','last','Roberts'),('en-US','last','Gomez'),
('en-US','last','Phillips'),('en-US','last','Evans'),('en-US','last','Turner'),
('en-US','last','Diaz'),('en-US','last','Parker'),('en-US','last','Cruz'),
('en-US','last','Edwards'),('en-US','last','Collins'),('en-US','last','Reyes'),
('en-US','last','Stewart'),('en-US','last','Morris'),('en-US','last','Morales'),
('en-US','last','Murphy'),('en-US','last','Cook'),('en-US','last','Rogers'),
('en-US','last','Gutierrez'),('en-US','last','Ortiz'),('en-US','last','Morgan'),
('en-US','last','Cooper'),('en-US','last','Peterson'),('en-US','last','Bailey'),
('en-US','last','Reed'),('en-US','last','Kelly'),('en-US','last','Howard'),
('en-US','last','Ramos'),('en-US','last','Kim'),('en-US','last','Cox'),
('en-US','last','Ward'),('en-US','last','Richardson'),('en-US','last','Watson'),
('en-US','last','Brooks'),('en-US','last','Chavez'),('en-US','last','Wood'),
('en-US','last','James'),('en-US','last','Bennett'),('en-US','last','Gray'),
('en-US','last','Mendoza'),('en-US','last','Ruiz'),('en-US','last','Hughes'),
('en-US','last','Price'),('en-US','last','Alvarez'),('en-US','last','Castillo'),
('en-US','last','Sanders'),('en-US','last','Patel'),('en-US','last','Myers'),
('en-US','last','Long'),('en-US','last','Ross'),('en-US','last','Foster'),
('en-US','last','Jimenez'),('en-US','last','Powell'),('en-US','last','Jenkins'),
('en-US','last','Perry'),('en-US','last','Russell'),('en-US','last','Sullivan'),
('en-US','last','Bell'),('en-US','last','Coleman'),('en-US','last','Butler'),
('en-US','last','Henderson'),('en-US','last','Barnes'),('en-US','last','Gonzales'),
('en-US','last','Fisher'),('en-US','last','Vasquez'),('en-US','last','Simmons'),
('en-US','last','Romero'),('en-US','last','Jordan'),('en-US','last','Patterson'),
('en-US','last','Alexander'),('en-US','last','Hamilton'),('en-US','last','Graham'),
('en-US','last','Reynolds'),('en-US','last','Griffin'),('en-US','last','Wallace'),
('en-US','last','Moreno'),('en-US','last','West'),('en-US','last','Cole'),
('en-US','last','Hayes'),('en-US','last','Bryant'),('en-US','last','Herrera'),
('en-US','last','Gibson'),('en-US','last','Ellis'),('en-US','last','Tran'),
('en-US','last','Medina'),('en-US','last','Aguilar'),('en-US','last','Stevens'),
('en-US','last','Murray'),('en-US','last','Ford'),('en-US','last','Castro'),
('en-US','last','Marshall'),('en-US','last','Owens'),('en-US','last','Harrison'),
('en-US','last','Fernandez'),('en-US','last','Mcdonald'),('en-US','last','Woods'),
('en-US','last','Washington'),('en-US','last','Kennedy'),('en-US','last','Wells'),
('en-US','last','Vargas'),('en-US','last','Henry'),('en-US','last','Chen'),
('en-US','last','Freeman'),('en-US','last','Webb'),('en-US','last','Tucker'),
('en-US','last','Guzman'),('en-US','last','Burns'),('en-US','last','Crawford'),
('en-US','last','Olson'),('en-US','last','Simpson'),('en-US','last','Porter'),
('en-US','last','Hunter'),('en-US','last','Gordon'),('en-US','last','Mendez'),
('en-US','last','Silva'),('en-US','last','Shaw'),('en-US','last','Snyder'),
('en-US','last','Mason'),('en-US','last','Dixon'),('en-US','last','Munoz'),
('en-US','last','Hunt'),('en-US','last','Hicks'),('en-US','last','Holmes'),
('en-US','last','Palmer'),('en-US','last','Wagner'),('en-US','last','Black'),
('en-US','last','Robertson'),('en-US','last','Boyd'),('en-US','last','Rose'),
('en-US','last','Stone'),('en-US','last','Salazar'),('en-US','last','Fox'),
('en-US','last','Warren'),('en-US','last','Mills'),('en-US','last','Meyer'),
('en-US','last','Rice'),('en-US','last','Schmidt'),('en-US','last','Garza'),
('en-US','last','Daniels'),('en-US','last','Ferguson'),('en-US','last','Nichols'),
('en-US','last','Stephens'),('en-US','last','Soto'),('en-US','last','Weaver'),
('en-US','last','Ryan'),('en-US','last','Gardner'),('en-US','last','Payne'),
('en-US','last','Grant'),('en-US','last','Dunn'),('en-US','last','Kelley'),
('en-US','last','Spencer'),('en-US','last','Hawkins'),('en-US','last','Arnold'),
('en-US','last','Pierce'),('en-US','last','Vazquez'),('en-US','last','Hansen'),
('en-US','last','Peters'),('en-US','last','Santos'),('en-US','last','Hart'),
('en-US','last','Bradley'),('en-US','last','Knight'),('en-US','last','Elliott'),
('en-US','last','Cunningham'),('en-US','last','Duncan'),('en-US','last','Armstrong'),
('en-US','last','Hudson'),('en-US','last','Carroll'),('en-US','last','Lane'),
('en-US','last','Riley'),('en-US','last','Andrews'),('en-US','last','Alvarado'),
('en-US','last','Ray'),('en-US','last','Delgado'),('en-US','last','Berry'),
('en-US','last','Perkins'),('en-US','last','Hoffman'),('en-US','last','Johnston'),
('en-US','last','Matthews'),('en-US','last','Pena'),('en-US','last','Richards'),
('en-US','last','Contreras'),('en-US','last','Willis'),('en-US','last','Carpenter'),
('en-US','last','Lawrence'),('en-US','last','Sandoval'),('en-US','last','Guerrero'),
('en-US','last','George'),('en-US','last','Chapman'),('en-US','last','Rios'),
('en-US','last','Estrada'),('en-US','last','Ortega'),('en-US','last','Watkins'),
('en-US','last','Greene'),('en-US','last','Nunez'),('en-US','last','Wheeler'),
('en-US','last','Valdez'),('en-US','last','Harper'),('en-US','last','Burke'),
('en-US','last','Larson'),('en-US','last','Santiago'),('en-US','last','Maldonado'),
('en-US','last','Morrison'),('en-US','last','Franklin'),('en-US','last','Carlson'),
('en-US','last','Austin'),('en-US','last','Dominguez'),('en-US','last','Carr'),
('en-US','last','Mckinney'),('en-US','last','Rios'),('en-US','last','Schneider'),
('en-US','last','Williamson'),('en-US','last','Bates'),('en-US','last','Walton'),
('en-US','last','Drake'),('en-US','last','Barker'),('en-US','last','Reeves'),
('en-US','last','Garner'),('en-US','last','Thornton'),('en-US','last','Newton'),
('en-US','last','Burke'),('en-US','last','Abbott'),('en-US','last','Pope'),
('en-US','last','Mccarthy'),('en-US','last','Fleming'),('en-US','last','Holt'),
('en-US','last','Morrow'),('en-US','last','Cannon'),('en-US','last','Tanner'),
('en-US','last','Boyd'),('en-US','last','Moody'),('en-US','last','Shields'),
('en-US','last','Mann'),('en-US','last','Lyons'),('en-US','last','Mack'),
('en-US','last','Norman'),('en-US','last','Day'),('en-US','last','Mcguire'),
('en-US','last','Lynn'),('en-US','last','Harrington'),('en-US','last','Boone'),
('en-US','last','Bowman'),('en-US','last','Summers'),('en-US','last','York'),
('en-US','last','Baldwin'),('en-US','last','Cross'),('en-US','last','Francis'),
('en-US','last','Bauer'),('en-US','last','Conner'),('en-US','last','Pitts'),
('en-US','last','Atkins'),('en-US','last','Vance'),('en-US','last','Todd'),
('en-US','last','Becker'),('en-US','last','Bass'),('en-US','last','Mcfarland'),
('en-US','last','Moon'),('en-US','last','Watkins'),('en-US','last','Ingram'),
('en-US','last','Barber'),('en-US','last','Luna'),('en-US','last','Ibarra'),
('en-US','last','Blake'),('en-US','last','Patrick'),('en-US','last','Pham'),
('en-US','last','Oconnor'),('en-US','last','Avery'),('en-US','last','Mcclain'),
('en-US','last','Felix'),('en-US','last','Chandler'),('en-US','last','Rivas'),
('en-US','last','Hubbard'),('en-US','last','Morton'),('en-US','last','Mcgee'),
('en-US','last','Mcbride'),('en-US','last','Giles'),('en-US','last','Trujillo'),
('en-US','last','Lambert'),('en-US','last','Odom'),('en-US','last','Curry'),
('en-US','last','Hampton'),('en-US','last','Page'),('en-US','last','Mccall'),
('en-US','last','Calhoun'),('en-US','last','Decker'),('en-US','last','Briggs'),
('en-US','last','Ayala'),('en-US','last','Knapp'),('en-US','last','Best'),
('en-US','last','Gates'),('en-US','last','Lowery'),('en-US','last','Watts'),
('en-US','last','Howe'),('en-US','last','Rollins'),('en-US','last','Barnett'),
('en-US','last','Pittman'),('en-US','last','Lindsey'),('en-US','last','Oneill'),
('en-US','last','Leblanc'),('en-US','last','Mullen'),('en-US','last','Wilder'),
('en-US','last','Fuentes'),('en-US','last','Suarez'),('en-US','last','Buchanan'),
('en-US','last','Reyes'),('en-US','last','Horton'),('en-US','last','Terrell'),
('en-US','last','Durham'),('en-US','last','Dickson'),('en-US','last','Malone'),
('en-US','last','Navarro'),('en-US','last','Gallagher'),('en-US','last','Cobb'),
('en-US','last','Miranda'),('en-US','last','Shaffer'),('en-US','last','Park'),
('en-US','last','Moran'),('en-US','last','Mooney'),('en-US','last','Bridges'),
('en-US','last','Pacheco'),('en-US','last','Cervantes'),('en-US','last','Roman'),
('en-US','last','Whitfield'),('en-US','last','Holman'),('en-US','last','Combs'),
('en-US','last','Mcpherson'),('en-US','last','Hensley'),('en-US','last','Church'),
('en-US','last','Moran'),('en-US','last','Osborn'),('en-US','last','Sears'),
('en-US','last','Drake'),('en-US','last','Solis'),('en-US','last','Vega'),
('en-US','last','Acosta'),('en-US','last','Mejia'),('en-US','last','Bernal'),
('en-US','last','Ochoa'),('en-US','last','Quintero'),('en-US','last','Arias'),
('en-US','last','Rubio'),('en-US','last','Lara'),('en-US','last','Cortez'),
('en-US','last','Campos'),('en-US','last','Vargas'),('en-US','last','Espinoza');

-- ────────────────────────────────────────────────────────────
-- EN-US  Titles
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','title_male','Mr.'),('en-US','title_male','Dr.'),
('en-US','title_male','Prof.'),('en-US','title_male','Rev.'),
('en-US','title_female','Ms.'),('en-US','title_female','Mrs.'),
('en-US','title_female','Dr.'),('en-US','title_female','Prof.'),
('en-US','title_female','Miss');

-- ────────────────────────────────────────────────────────────
-- EN-US  Street names (120)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','street_name','Maple'),('en-US','street_name','Oak'),('en-US','street_name','Pine'),
('en-US','street_name','Cedar'),('en-US','street_name','Elm'),('en-US','street_name','Walnut'),
('en-US','street_name','Birch'),('en-US','street_name','Spruce'),('en-US','street_name','Willow'),
('en-US','street_name','Ash'),('en-US','street_name','Magnolia'),('en-US','street_name','Cherry'),
('en-US','street_name','Poplar'),('en-US','street_name','Hickory'),('en-US','street_name','Chestnut'),
('en-US','street_name','Main'),('en-US','street_name','First'),('en-US','street_name','Second'),
('en-US','street_name','Third'),('en-US','street_name','Fourth'),('en-US','street_name','Fifth'),
('en-US','street_name','Sixth'),('en-US','street_name','Seventh'),('en-US','street_name','Eighth'),
('en-US','street_name','Ninth'),('en-US','street_name','Tenth'),('en-US','street_name','Park'),
('en-US','street_name','Lake'),('en-US','street_name','Hill'),('en-US','street_name','Valley'),
('en-US','street_name','River'),('en-US','street_name','Forest'),('en-US','street_name','Meadow'),
('en-US','street_name','Sunset'),('en-US','street_name','Sunrise'),('en-US','street_name','Spring'),
('en-US','street_name','Summer'),('en-US','street_name','Autumn'),('en-US','street_name','Winter'),
('en-US','street_name','Lakeview'),('en-US','street_name','Hillside'),('en-US','street_name','Riverside'),
('en-US','street_name','Fairview'),('en-US','street_name','Greenwood'),('en-US','street_name','Brookside'),
('en-US','street_name','Ridgewood'),('en-US','street_name','Creekside'),('en-US','street_name','Clearwater'),
('en-US','street_name','Highview'),('en-US','street_name','Woodbridge'),('en-US','street_name','Stonegate'),
('en-US','street_name','Heritage'),('en-US','street_name','Liberty'),('en-US','street_name','Independence'),
('en-US','street_name','Freedom'),('en-US','street_name','Justice'),('en-US','street_name','Lincoln'),
('en-US','street_name','Washington'),('en-US','street_name','Jefferson'),('en-US','street_name','Madison'),
('en-US','street_name','Monroe'),('en-US','street_name','Adams'),('en-US','street_name','Franklin'),
('en-US','street_name','Grant'),('en-US','street_name','Sherman'),('en-US','street_name','Lee'),
('en-US','street_name','Jackson'),('en-US','street_name','Wilson'),('en-US','street_name','Roosevelt'),
('en-US','street_name','Kennedy'),('en-US','street_name','King'),('en-US','street_name','Pioneer'),
('en-US','street_name','Colonial'),('en-US','street_name','Colonial'),('en-US','street_name','Frontier'),
('en-US','street_name','Prairie'),('en-US','street_name','Horizon'),('en-US','street_name','Panorama'),
('en-US','street_name','Lakeshore'),('en-US','street_name','Bayview'),('en-US','street_name','Harborview'),
('en-US','street_name','Highland'),('en-US','street_name','Lowland'),('en-US','street_name','Fernwood'),
('en-US','street_name','Briarwood'),('en-US','street_name','Maplewood'),('en-US','street_name','Elmwood'),
('en-US','street_name','Crestwood'),('en-US','street_name','Pinewood'),('en-US','street_name','Cedarwood'),
('en-US','street_name','Birchwood'),('en-US','street_name','Oakwood'),('en-US','street_name','Hazelwood'),
('en-US','street_name','Driftwood'),('en-US','street_name','Deerfield'),('en-US','street_name','Springfield'),
('en-US','street_name','Greenfield'),('en-US','street_name','Plainfield'),('en-US','street_name','Bloomfield'),
('en-US','street_name','Fairfield'),('en-US','street_name','Westfield'),('en-US','street_name','Sheffield'),
('en-US','street_name','Millfield'),('en-US','street_name','Redwood'),('en-US','street_name','Sequoia'),
('en-US','street_name','Aspen'),('en-US','street_name','Cypress'),('en-US','street_name','Juniper'),
('en-US','street_name','Sycamore'),('en-US','street_name','Cottonwood'),('en-US','street_name','Laurel'),
('en-US','street_name','Boxwood'),('en-US','street_name','Dogwood'),('en-US','street_name','Rosewood'),
('en-US','street_name','Timberline'),('en-US','street_name','Ridgeline'),('en-US','street_name','Shoreline');

-- ────────────────────────────────────────────────────────────
-- EN-US  Street suffixes
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','street_suffix','Street'),('en-US','street_suffix','Avenue'),
('en-US','street_suffix','Boulevard'),('en-US','street_suffix','Drive'),
('en-US','street_suffix','Lane'),('en-US','street_suffix','Road'),
('en-US','street_suffix','Way'),('en-US','street_suffix','Court'),
('en-US','street_suffix','Place'),('en-US','street_suffix','Circle'),
('en-US','street_suffix','Trail'),('en-US','street_suffix','Terrace');

-- ────────────────────────────────────────────────────────────
-- EN-US  Cities (JSON format: city, state, zip pattern)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','city','{"city":"New York","state":"NY","zip":"#####"}'),
('en-US','city','{"city":"Los Angeles","state":"CA","zip":"9####"}'),
('en-US','city','{"city":"Chicago","state":"IL","zip":"6####"}'),
('en-US','city','{"city":"Houston","state":"TX","zip":"7####"}'),
('en-US','city','{"city":"Phoenix","state":"AZ","zip":"85###"}'),
('en-US','city','{"city":"Philadelphia","state":"PA","zip":"19###"}'),
('en-US','city','{"city":"San Antonio","state":"TX","zip":"78###"}'),
('en-US','city','{"city":"San Diego","state":"CA","zip":"921##"}'),
('en-US','city','{"city":"Dallas","state":"TX","zip":"752##"}'),
('en-US','city','{"city":"San Jose","state":"CA","zip":"951##"}'),
('en-US','city','{"city":"Austin","state":"TX","zip":"787##"}'),
('en-US','city','{"city":"Jacksonville","state":"FL","zip":"322##"}'),
('en-US','city','{"city":"Fort Worth","state":"TX","zip":"761##"}'),
('en-US','city','{"city":"Columbus","state":"OH","zip":"432##"}'),
('en-US','city','{"city":"Charlotte","state":"NC","zip":"282##"}'),
('en-US','city','{"city":"Indianapolis","state":"IN","zip":"462##"}'),
('en-US','city','{"city":"San Francisco","state":"CA","zip":"941##"}'),
('en-US','city','{"city":"Seattle","state":"WA","zip":"981##"}'),
('en-US','city','{"city":"Denver","state":"CO","zip":"802##"}'),
('en-US','city','{"city":"Nashville","state":"TN","zip":"372##"}'),
('en-US','city','{"city":"Oklahoma City","state":"OK","zip":"731##"}'),
('en-US','city','{"city":"El Paso","state":"TX","zip":"799##"}'),
('en-US','city','{"city":"Boston","state":"MA","zip":"021##"}'),
('en-US','city','{"city":"Portland","state":"OR","zip":"972##"}'),
('en-US','city','{"city":"Las Vegas","state":"NV","zip":"891##"}'),
('en-US','city','{"city":"Memphis","state":"TN","zip":"381##"}'),
('en-US','city','{"city":"Louisville","state":"KY","zip":"402##"}'),
('en-US','city','{"city":"Baltimore","state":"MD","zip":"212##"}'),
('en-US','city','{"city":"Milwaukee","state":"WI","zip":"532##"}'),
('en-US','city','{"city":"Albuquerque","state":"NM","zip":"871##"}'),
('en-US','city','{"city":"Tucson","state":"AZ","zip":"857##"}'),
('en-US','city','{"city":"Fresno","state":"CA","zip":"937##"}'),
('en-US','city','{"city":"Sacramento","state":"CA","zip":"958##"}'),
('en-US','city','{"city":"Mesa","state":"AZ","zip":"852##"}'),
('en-US','city','{"city":"Atlanta","state":"GA","zip":"303##"}'),
('en-US','city','{"city":"Kansas City","state":"MO","zip":"641##"}'),
('en-US','city','{"city":"Omaha","state":"NE","zip":"681##"}'),
('en-US','city','{"city":"Colorado Springs","state":"CO","zip":"809##"}'),
('en-US','city','{"city":"Raleigh","state":"NC","zip":"276##"}'),
('en-US','city','{"city":"Miami","state":"FL","zip":"331##"}'),
('en-US','city','{"city":"Cleveland","state":"OH","zip":"441##"}'),
('en-US','city','{"city":"Tulsa","state":"OK","zip":"741##"}'),
('en-US','city','{"city":"Minneapolis","state":"MN","zip":"554##"}'),
('en-US','city','{"city":"Tampa","state":"FL","zip":"336##"}'),
('en-US','city','{"city":"New Orleans","state":"LA","zip":"701##"}'),
('en-US','city','{"city":"Arlington","state":"TX","zip":"760##"}'),
('en-US','city','{"city":"Wichita","state":"KS","zip":"672##"}'),
('en-US','city','{"city":"Aurora","state":"CO","zip":"800##"}'),
('en-US','city','{"city":"Bakersfield","state":"CA","zip":"933##"}'),
('en-US','city','{"city":"Cincinnati","state":"OH","zip":"452##"}');

-- ────────────────────────────────────────────────────────────
-- EN-US  Eye colors
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','eye_color','Brown'),('en-US','eye_color','Blue'),
('en-US','eye_color','Green'),('en-US','eye_color','Hazel'),
('en-US','eye_color','Gray'),('en-US','eye_color','Amber');

-- ════════════════════════════════════════════════════════════
-- DE-DE DATA
-- ════════════════════════════════════════════════════════════

-- ────────────────────────────────────────────────────────────
-- DE-DE  Male first names (150)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','first_male','Alexander'),('de-DE','first_male','Andreas'),('de-DE','first_male','Benjamin'),
('de-DE','first_male','Christian'),('de-DE','first_male','Daniel'),('de-DE','first_male','David'),
('de-DE','first_male','Dennis'),('de-DE','first_male','Dominik'),('de-DE','first_male','Erik'),
('de-DE','first_male','Fabian'),('de-DE','first_male','Felix'),('de-DE','first_male','Florian'),
('de-DE','first_male','Frank'),('de-DE','first_male','Friedrich'),('de-DE','first_male','Georg'),
('de-DE','first_male','Hans'),('de-DE','first_male','Helmut'),('de-DE','first_male','Henrik'),
('de-DE','first_male','Jakob'),('de-DE','first_male','Jan'),('de-DE','first_male','Jonas'),
('de-DE','first_male','Jürgen'),('de-DE','first_male','Karl'),('de-DE','first_male','Klaus'),
('de-DE','first_male','Lars'),('de-DE','first_male','Leon'),('de-DE','first_male','Lukas'),
('de-DE','first_male','Marc'),('de-DE','first_male','Markus'),('de-DE','first_male','Martin'),
('de-DE','first_male','Matthias'),('de-DE','first_male','Max'),('de-DE','first_male','Michael'),
('de-DE','first_male','Moritz'),('de-DE','first_male','Nico'),('de-DE','first_male','Niklas'),
('de-DE','first_male','Oliver'),('de-DE','first_male','Patrick'),('de-DE','first_male','Paul'),
('de-DE','first_male','Peter'),('de-DE','first_male','Philipp'),('de-DE','first_male','Rafael'),
('de-DE','first_male','Rolf'),('de-DE','first_male','Rudolf'),('de-DE','first_male','Sebastian'),
('de-DE','first_male','Simon'),('de-DE','first_male','Stefan'),('de-DE','first_male','Thomas'),
('de-DE','first_male','Tobias'),('de-DE','first_male','Tom'),('de-DE','first_male','Uwe'),
('de-DE','first_male','Valentin'),('de-DE','first_male','Viktor'),('de-DE','first_male','Walter'),
('de-DE','first_male','Wilhelm'),('de-DE','first_male','Wolfgang'),('de-DE','first_male','Christoph'),
('de-DE','first_male','Erich'),('de-DE','first_male','Ernst'),('de-DE','first_male','Franz'),
('de-DE','first_male','Fritz'),('de-DE','first_male','Gerhard'),('de-DE','first_male','Gottfried'),
('de-DE','first_male','Günter'),('de-DE','first_male','Heinrich'),('de-DE','first_male','Herbert'),
('de-DE','first_male','Herman'),('de-DE','first_male','Horst'),('de-DE','first_male','Joachim'),
('de-DE','first_male','Jochen'),('de-DE','first_male','Joerg'),('de-DE','first_male','Johann'),
('de-DE','first_male','Johannes'),('de-DE','first_male','Josef'),('de-DE','first_male','Kurt'),
('de-DE','first_male','Ludwig'),('de-DE','first_male','Manfred'),('de-DE','first_male','Norbert'),
('de-DE','first_male','Otto'),('de-DE','first_male','Rainer'),('de-DE','first_male','Reinhard'),
('de-DE','first_male','Richard'),('de-DE','first_male','Robert'),('de-DE','first_male','Sigfried'),
('de-DE','first_male','Werner'),('de-DE','first_male','Anton'),('de-DE','first_male','Arnold'),
('de-DE','first_male','Benedikt'),('de-DE','first_male','Bernd'),('de-DE','first_male','Bruno'),
('de-DE','first_male','Dieter'),('de-DE','first_male','Dietrich'),('de-DE','first_male','Dietmar'),
('de-DE','first_male','Eduard'),('de-DE','first_male','Emil'),('de-DE','first_male','Engelbert'),
('de-DE','first_male','Ferdinand'),('de-DE','first_male','Fridolin'),('de-DE','first_male','Gregor'),
('de-DE','first_male','Hannes'),('de-DE','first_male','Ingo'),('de-DE','first_male','Konrad'),
('de-DE','first_male','Lutz'),('de-DE','first_male','Marco'),('de-DE','first_male','Nils'),
('de-DE','first_male','Pascal'),('de-DE','first_male','René'),('de-DE','first_male','Rene'),
('de-DE','first_male','Sascha'),('de-DE','first_male','Sven'),('de-DE','first_male','Theodor'),
('de-DE','first_male','Tilman'),('de-DE','first_male','Ulrich'),('de-DE','first_male','Axel'),
('de-DE','first_male','Bastian'),('de-DE','first_male','Christof'),('de-DE','first_male','Damian'),
('de-DE','first_male','Elias'),('de-DE','first_male','Emil'),('de-DE','first_male','Emilio'),
('de-DE','first_male','Finn'),('de-DE','first_male','Hannes'),('de-DE','first_male','Hugo'),
('de-DE','first_male','Karl-Heinz'),('de-DE','first_male','Klaus-Peter'),('de-DE','first_male','Kilian'),
('de-DE','first_male','Lennart'),('de-DE','first_male','Lenz'),('de-DE','first_male','Leo'),
('de-DE','first_male','Levin'),('de-DE','first_male','Liam'),('de-DE','first_male','Luca'),
('de-DE','first_male','Luis'),('de-DE','first_male','Maximilian'),('de-DE','first_male','Milan'),
('de-DE','first_male','Milo'),('de-DE','first_male','Mirko'),('de-DE','first_male','Morten'),
('de-DE','first_male','Finn'),('de-DE','first_male','Noah'),('de-DE','first_male','Ole'),
('de-DE','first_male','Oskar'),('de-DE','first_male','Ralf'),('de-DE','first_male','Ramon'),
('de-DE','first_male','Rico'),('de-DE','first_male','Rudi'),('de-DE','first_male','Samuel'),
('de-DE','first_male','Sandro'),('de-DE','first_male','Sören'),('de-DE','first_male','Thorsten'),
('de-DE','first_male','Till'),('de-DE','first_male','Timo'),('de-DE','first_male','Tim'),
('de-DE','first_male','Toni'),('de-DE','first_male','Torsten');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Female first names (150)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','first_female','Alina'),('de-DE','first_female','Andrea'),('de-DE','first_female','Angela'),
('de-DE','first_female','Angelika'),('de-DE','first_female','Anna'),('de-DE','first_female','Annegret'),
('de-DE','first_female','Anneliese'),('de-DE','first_female','Annette'),('de-DE','first_female','Antje'),
('de-DE','first_female','Bianca'),('de-DE','first_female','Birgit'),('de-DE','first_female','Brigitte'),
('de-DE','first_female','Carina'),('de-DE','first_female','Carmen'),('de-DE','first_female','Christina'),
('de-DE','first_female','Christine'),('de-DE','first_female','Clara'),('de-DE','first_female','Claudia'),
('de-DE','first_female','Daniela'),('de-DE','first_female','Diana'),('de-DE','first_female','Doris'),
('de-DE','first_female','Elisabeth'),('de-DE','first_female','Else'),('de-DE','first_female','Eva'),
('de-DE','first_female','Franziska'),('de-DE','first_female','Frieda'),('de-DE','first_female','Gabi'),
('de-DE','first_female','Gabriele'),('de-DE','first_female','Gerda'),('de-DE','first_female','Gisela'),
('de-DE','first_female','Hannah'),('de-DE','first_female','Hanna'),('de-DE','first_female','Hannelore'),
('de-DE','first_female','Heike'),('de-DE','first_female','Helga'),('de-DE','first_female','Hildegard'),
('de-DE','first_female','Ilse'),('de-DE','first_female','Ines'),('de-DE','first_female','Ingrid'),
('de-DE','first_female','Iris'),('de-DE','first_female','Jana'),('de-DE','first_female','Jennifer'),
('de-DE','first_female','Jessica'),('de-DE','first_female','Julia'),('de-DE','first_female','Judith'),
('de-DE','first_female','Karen'),('de-DE','first_female','Karin'),('de-DE','first_female','Karla'),
('de-DE','first_female','Katarina'),('de-DE','first_female','Katharina'),('de-DE','first_female','Katrin'),
('de-DE','first_female','Laura'),('de-DE','first_female','Lena'),('de-DE','first_female','Lisa'),
('de-DE','first_female','Luisa'),('de-DE','first_female','Magdalena'),('de-DE','first_female','Maria'),
('de-DE','first_female','Martina'),('de-DE','first_female','Monika'),('de-DE','first_female','Nadine'),
('de-DE','first_female','Nicole'),('de-DE','first_female','Petra'),('de-DE','first_female','Renate'),
('de-DE','first_female','Rita'),('de-DE','first_female','Sabine'),('de-DE','first_female','Sandra'),
('de-DE','first_female','Sara'),('de-DE','first_female','Sarah'),('de-DE','first_female','Silke'),
('de-DE','first_female','Sonja'),('de-DE','first_female','Stefanie'),('de-DE','first_female','Susanne'),
('de-DE','first_female','Tanja'),('de-DE','first_female','Ulrike'),('de-DE','first_female','Ursula'),
('de-DE','first_female','Verena'),('de-DE','first_female','Veronika'),('de-DE','first_female','Waltraud'),
('de-DE','first_female','Yvonne'),('de-DE','first_female','Johanna'),('de-DE','first_female','Klara'),
('de-DE','first_female','Lea'),('de-DE','first_female','Leonie'),('de-DE','first_female','Lotte'),
('de-DE','first_female','Marie'),('de-DE','first_female','Mia'),('de-DE','first_female','Mina'),
('de-DE','first_female','Nora'),('de-DE','first_female','Olivia'),('de-DE','first_female','Paula'),
('de-DE','first_female','Sophie'),('de-DE','first_female','Sophia'),('de-DE','first_female','Vera'),
('de-DE','first_female','Astrid'),('de-DE','first_female','Bettina'),('de-DE','first_female','Charlotte'),
('de-DE','first_female','Emma'),('de-DE','first_female','Friederike'),('de-DE','first_female','Greta'),
('de-DE','first_female','Hilde'),('de-DE','first_female','Irmgard'),('de-DE','first_female','Karoline'),
('de-DE','first_female','Lieselotte'),('de-DE','first_female','Luise'),('de-DE','first_female','Margit'),
('de-DE','first_female','Marlene'),('de-DE','first_female','Meike'),('de-DE','first_female','Mila'),
('de-DE','first_female','Miriam'),('de-DE','first_female','Nathalie'),('de-DE','first_female','Rosa'),
('de-DE','first_female','Roswitha'),('de-DE','first_female','Sigrid'),('de-DE','first_female','Simone'),
('de-DE','first_female','Theresa'),('de-DE','first_female','Thea'),('de-DE','first_female','Trude'),
('de-DE','first_female','Wanda'),('de-DE','first_female','Wilma'),('de-DE','first_female','Anja'),
('de-DE','first_female','Ariane'),('de-DE','first_female','Aurelia'),('de-DE','first_female','Corinna'),
('de-DE','first_female','Elke'),('de-DE','first_female','Elvira'),('de-DE','first_female','Emilia'),
('de-DE','first_female','Gesine'),('de-DE','first_female','Gunda'),('de-DE','first_female','Imke'),
('de-DE','first_female','Jette'),('de-DE','first_female','Jutta'),('de-DE','first_female','Kirsten'),
('de-DE','first_female','Kerstin'),('de-DE','first_female','Kristina'),('de-DE','first_female','Lara'),
('de-DE','first_female','Liane'),('de-DE','first_female','Linda'),('de-DE','first_female','Loni'),
('de-DE','first_female','Maja'),('de-DE','first_female','Maike'),('de-DE','first_female','Manuela'),
('de-DE','first_female','Margret'),('de-DE','first_female','Marion'),('de-DE','first_female','Mechthild');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Middle names
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','middle_male','Klaus'),('de-DE','middle_male','Hans'),('de-DE','middle_male','Wilhelm'),
('de-DE','middle_male','Karl'),('de-DE','middle_male','Johann'),('de-DE','middle_male','Heinrich'),
('de-DE','middle_male','Heinz'),('de-DE','middle_male','Ludwig'),('de-DE','middle_male','Friedrich'),
('de-DE','middle_male','Ernst'),('de-DE','middle_male','Dieter'),('de-DE','middle_male','Jürgen'),
('de-DE','middle_male','Peter'),('de-DE','middle_male','Otto'),('de-DE','middle_male','Rolf'),
('de-DE','middle_male','Gerhard'),('de-DE','middle_male','Werner'),('de-DE','middle_male','Walter'),
('de-DE','middle_male','Erich'),('de-DE','middle_male','Josef');
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','middle_female','Maria'),('de-DE','middle_female','Anna'),('de-DE','middle_female','Sophie'),
('de-DE','middle_female','Katharina'),('de-DE','middle_female','Elisabeth'),('de-DE','middle_female','Rosa'),
('de-DE','middle_female','Liese'),('de-DE','middle_female','Inge'),('de-DE','middle_female','Ilse'),
('de-DE','middle_female','Edith'),('de-DE','middle_female','Grete'),('de-DE','middle_female','Lotte'),
('de-DE','middle_female','Helene'),('de-DE','middle_female','Martha'),('de-DE','middle_female','Emma');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Titles
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','title_male','Herr'),('de-DE','title_male','Dr.'),('de-DE','title_male','Prof.'),('de-DE','title_male','Dipl.-Ing.'),
('de-DE','title_female','Frau'),('de-DE','title_female','Dr.'),('de-DE','title_female','Prof.');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Last names (500)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','last','Müller'),('de-DE','last','Schmidt'),('de-DE','last','Schneider'),
('de-DE','last','Fischer'),('de-DE','last','Weber'),('de-DE','last','Meyer'),
('de-DE','last','Wagner'),('de-DE','last','Becker'),('de-DE','last','Schulz'),
('de-DE','last','Hoffmann'),('de-DE','last','Schäfer'),('de-DE','last','Koch'),
('de-DE','last','Bauer'),('de-DE','last','Richter'),('de-DE','last','Klein'),
('de-DE','last','Wolf'),('de-DE','last','Schröder'),('de-DE','last','Neumann'),
('de-DE','last','Schwarz'),('de-DE','last','Zimmermann'),('de-DE','last','Braun'),
('de-DE','last','Krüger'),('de-DE','last','Hofmann'),('de-DE','last','Hartmann'),
('de-DE','last','Lange'),('de-DE','last','Schmitt'),('de-DE','last','Werner'),
('de-DE','last','Schmitz'),('de-DE','last','Krause'),('de-DE','last','Meier'),
('de-DE','last','Lehmann'),('de-DE','last','Schmid'),('de-DE','last','Schulze'),
('de-DE','last','Maier'),('de-DE','last','Köhler'),('de-DE','last','Herrmann'),
('de-DE','last','König'),('de-DE','last','Walter'),('de-DE','last','Mayer'),
('de-DE','last','Huber'),('de-DE','last','Kaiser'),('de-DE','last','Fuchs'),
('de-DE','last','Peters'),('de-DE','last','Lang'),('de-DE','last','Scholz'),
('de-DE','last','Möller'),('de-DE','last','Weiß'),('de-DE','last','Jung'),
('de-DE','last','Hahn'),('de-DE','last','Schubert'),('de-DE','last','Vogel'),
('de-DE','last','Friedrich'),('de-DE','last','Frank'),('de-DE','last','Berger'),
('de-DE','last','Keller'),('de-DE','last','Sommer'),('de-DE','last','Groß'),
('de-DE','last','Seidel'),('de-DE','last','Brandt'),('de-DE','last','Haas'),
('de-DE','last','Schreiber'),('de-DE','last','Graf'),('de-DE','last','Schulte'),
('de-DE','last','Dietrich'),('de-DE','last','Ziegler'),('de-DE','last','Kuhn'),
('de-DE','last','Kühn'),('de-DE','last','Pohl'),('de-DE','last','Engel'),
('de-DE','last','Horn'),('de-DE','last','Busch'),('de-DE','last','Vogt'),
('de-DE','last','Simon'),('de-DE','last','Roth'),('de-DE','last','Wiedemann'),
('de-DE','last','Thomas'),('de-DE','last','Franke'),('de-DE','last','Albrecht'),
('de-DE','last','Böhm'),('de-DE','last','Winter'),('de-DE','last','Kramer'),
('de-DE','last','Ludwig'),('de-DE','last','Baumann'),('de-DE','last','Lorenz'),
('de-DE','last','Pfeiffer'),('de-DE','last','Günther'),('de-DE','last','Bruns'),
('de-DE','last','Vogt'),('de-DE','last','Arnold'),('de-DE','last','Hesse'),
('de-DE','last','Henning'),('de-DE','last','Kübler'),('de-DE','last','Mertens'),
('de-DE','last','Bergmann'),('de-DE','last','Otto'),('de-DE','last','Mann'),
('de-DE','last','Ritter'),('de-DE','last','Ernst'),('de-DE','last','Schwab'),
('de-DE','last','Renner'),('de-DE','last','Lenz'),('de-DE','last','Haase'),
('de-DE','last','Kolb'),('de-DE','last','Eichler'),('de-DE','last','Thoma'),
('de-DE','last','Noll'),('de-DE','last','Kessler'),('de-DE','last','Stoll'),
('de-DE','last','Conrad'),('de-DE','last','Petersen'),('de-DE','last','Kohl'),
('de-DE','last','Brauer'),('de-DE','last','Rothe'),('de-DE','last','Geyer'),
('de-DE','last','Hinz'),('de-DE','last','Küster'),('de-DE','last','Jäger'),
('de-DE','last','Sauer'),('de-DE','last','Fink'),('de-DE','last','Stein'),
('de-DE','last','Löffler'),('de-DE','last','Heinze'),('de-DE','last','Winkler'),
('de-DE','last','Böttcher'),('de-DE','last','Grimm'),('de-DE','last','Lohmann'),
('de-DE','last','Witt'),('de-DE','last','Fritz'),('de-DE','last','Abel'),
('de-DE','last','Kraft'),('de-DE','last','Frisch'),('de-DE','last','Rau'),
('de-DE','last','Sturm'),('de-DE','last','Henkel'),('de-DE','last','Steinbach'),
('de-DE','last','Kunze'),('de-DE','last','Krug'),('de-DE','last','Lindner'),
('de-DE','last','Nöll'),('de-DE','last','Reuter'),('de-DE','last','Hanke'),
('de-DE','last','Bock'),('de-DE','last','Kraus'),('de-DE','last','Brinkmann'),
('de-DE','last','Hamann'),('de-DE','last','Klose'),('de-DE','last','Dreyer'),
('de-DE','last','Wiese'),('de-DE','last','Rüttgers'),('de-DE','last','Schultze'),
('de-DE','last','Löhr'),('de-DE','last','Reinel'),('de-DE','last','Decker'),
('de-DE','last','Held'),('de-DE','last','Bothe'),('de-DE','last','Wendel'),
('de-DE','last','Renz'),('de-DE','last','Schönfeld'),('de-DE','last','Wulf'),
('de-DE','last','Gärtner'),('de-DE','last','Krebs'),('de-DE','last','Dorn'),
('de-DE','last','Fleischer'),('de-DE','last','Nagel'),('de-DE','last','Hiller'),
('de-DE','last','Reinhard'),('de-DE','last','Steger'),('de-DE','last','Blum'),
('de-DE','last','Rabe'),('de-DE','last','Keil'),('de-DE','last','Menz'),
('de-DE','last','Weisser'),('de-DE','last','Behrens'),('de-DE','last','Drescher'),
('de-DE','last','Freund'),('de-DE','last','Zander'),('de-DE','last','Probst'),
('de-DE','last','Kiefer'),('de-DE','last','Rohde'),('de-DE','last','Richter'),
('de-DE','last','Seidler'),('de-DE','last','Steinke'),('de-DE','last','Böll'),
('de-DE','last','Linke'),('de-DE','last','Frey'),('de-DE','last','Kraft'),
('de-DE','last','Rupp'),('de-DE','last','Heer'),('de-DE','last','Seeger'),
('de-DE','last','Stark'),('de-DE','last','Kamps'),('de-DE','last','Voß'),
('de-DE','last','Herz'),('de-DE','last','Herrmann'),('de-DE','last','Voss'),
('de-DE','last','Schultz'),('de-DE','last','Böhme'),('de-DE','last','Ebner'),
('de-DE','last','Schick'),('de-DE','last','Weis'),('de-DE','last','Zeller'),
('de-DE','last','Stock'),('de-DE','last','Hammer'),('de-DE','last','Schenk'),
('de-DE','last','Büttner'),('de-DE','last','Rühl'),('de-DE','last','Schuster'),
('de-DE','last','Hecht'),('de-DE','last','Beyer'),('de-DE','last','Münch'),
('de-DE','last','Amann'),('de-DE','last','Hartung'),('de-DE','last','Schrader'),
('de-DE','last','Westermann'),('de-DE','last','Faber'),('de-DE','last','Ott'),
('de-DE','last','Kasel'),('de-DE','last','Lauer'),('de-DE','last','Heinen'),
('de-DE','last','Sternberg'),('de-DE','last','Behl'),('de-DE','last','Hübner'),
('de-DE','last','Moll'),('de-DE','last','Weigand'),('de-DE','last','Winkel'),
('de-DE','last','Mende'),('de-DE','last','Mühlbach'),('de-DE','last','Kremer'),
('de-DE','last','Gottschalk'),('de-DE','last','Wendt'),('de-DE','last','Heinrichs'),
('de-DE','last','Schilling'),('de-DE','last','Klose'),('de-DE','last','Klose'),
('de-DE','last','Bergner'),('de-DE','last','Thies'),('de-DE','last','Breuer'),
('de-DE','last','Lauer'),('de-DE','last','Löwen'),('de-DE','last','Nissen'),
('de-DE','last','Pape'),('de-DE','last','Riedel'),('de-DE','last','Rode'),
('de-DE','last','Scholl'),('de-DE','last','Schramm'),('de-DE','last','Steffen'),
('de-DE','last','Tischer'),('de-DE','last','Unger'),('de-DE','last','Voelker'),
('de-DE','last','Waldmann'),('de-DE','last','Wedel'),('de-DE','last','Wildner'),
('de-DE','last','Zahn'),('de-DE','last','Bremer'),('de-DE','last','Gierke'),
('de-DE','last','Holtz'),('de-DE','last','Imhof'),('de-DE','last','Janssen'),
('de-DE','last','Kasten'),('de-DE','last','Kemper'),('de-DE','last','Laube'),
('de-DE','last','Liebers'),('de-DE','last','Meister'),('de-DE','last','Nett'),
('de-DE','last','Oppel'),('de-DE','last','Panzer'),('de-DE','last','Quast'),
('de-DE','last','Rösler'),('de-DE','last','Sauter'),('de-DE','last','Tröger'),
('de-DE','last','Ufer'),('de-DE','last','Vahl'),('de-DE','last','Wecker'),
('de-DE','last','Xander'),('de-DE','last','Zache'),('de-DE','last','Abell'),
('de-DE','last','Bach'),('de-DE','last','Clasen'),('de-DE','last','Drese'),
('de-DE','last','Ehrhardt'),('de-DE','last','Fröhlich'),('de-DE','last','Grothe'),
('de-DE','last','Hess'),('de-DE','last','Ihle'),('de-DE','last','Janz'),
('de-DE','last','Kellner'),('de-DE','last','Leppert'),('de-DE','last','Mrosek'),
('de-DE','last','Naber'),('de-DE','last','Obenaus'),('de-DE','last','Pehl'),
('de-DE','last','Quint'),('de-DE','last','Rapp'),('de-DE','last','Sander'),
('de-DE','last','Theiler'),('de-DE','last','Ulm'),('de-DE','last','Vogelsang'),
('de-DE','last','Wendler'),('de-DE','last','Xander'),('de-DE','last','Zeitz'),
('de-DE','last','Ambrosius'),('de-DE','last','Bartel'),('de-DE','last','Clemens'),
('de-DE','last','Dibbert'),('de-DE','last','Ebell'),('de-DE','last','Faust'),
('de-DE','last','Gerdts'),('de-DE','last','Hornig'),('de-DE','last','Irmler'),
('de-DE','last','Jording'),('de-DE','last','Korn'),('de-DE','last','Loeff'),
('de-DE','last','Mundt'),('de-DE','last','Nonn'),('de-DE','last','Ohr'),
('de-DE','last','Priebe'),('de-DE','last','Rohlen'),('de-DE','last','Stamm'),
('de-DE','last','Tempel'),('de-DE','last','Uhle'),('de-DE','last','Venner'),
('de-DE','last','Warnke'),('de-DE','last','Xylander'),('de-DE','last','Zobel'),
('de-DE','last','Ambos'),('de-DE','last','Berg'),('de-DE','last','Czech'),
('de-DE','last','Dobbert'),('de-DE','last','Eden'),('de-DE','last','Faul'),
('de-DE','last','Gerber'),('de-DE','last','Hensel'),('de-DE','last','Iken'),
('de-DE','last','Jordan'),('de-DE','last','Kast'),('de-DE','last','Loch'),
('de-DE','last','Maas'),('de-DE','last','Nack'),('de-DE','last','Ochel'),
('de-DE','last','Pahlke'),('de-DE','last','Rogge'),('de-DE','last','Salm'),
('de-DE','last','Tend'),('de-DE','last','Uhrig'),('de-DE','last','Vetter'),
('de-DE','last','Wend'),('de-DE','last','Yorck'),('de-DE','last','Zick');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Street names (100)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','street_name','Haupt'),('de-DE','street_name','Bahnhof'),('de-DE','street_name','Schul'),
('de-DE','street_name','Kirch'),('de-DE','street_name','Mühlen'),('de-DE','street_name','Garten'),
('de-DE','street_name','Wald'),('de-DE','street_name','Berg'),('de-DE','street_name','Wiesen'),
('de-DE','street_name','Linden'),('de-DE','street_name','Rosen'),('de-DE','street_name','Eichen'),
('de-DE','street_name','Birken'),('de-DE','street_name','Tannen'),('de-DE','street_name','Buchen'),
('de-DE','street_name','Kastanien'),('de-DE','street_name','Ahornblatt'),('de-DE','street_name','Ulmen'),
('de-DE','street_name','Fichten'),('de-DE','street_name','Kiefern'),('de-DE','street_name','Erlen'),
('de-DE','street_name','Weiden'),('de-DE','street_name','Pappeln'),('de-DE','street_name','Nußbaum'),
('de-DE','street_name','Holunder'),('de-DE','street_name','Erdbeer'),('de-DE','street_name','Weinberg'),
('de-DE','street_name','Obstgarten'),('de-DE','street_name','Brücken'),('de-DE','street_name','Ufer'),
('de-DE','street_name','Markt'),('de-DE','street_name','Ring'),('de-DE','street_name','Bahn'),
('de-DE','street_name','Post'),('de-DE','street_name','Rathaus'),('de-DE','street_name','Park'),
('de-DE','street_name','Burg'),('de-DE','street_name','Schloss'),('de-DE','street_name','Kloster'),
('de-DE','street_name','Dom'),('de-DE','street_name','Bismarck'),('de-DE','street_name','Kaiser'),
('de-DE','street_name','Königs'),('de-DE','street_name','Fürsten'),('de-DE','street_name','Herzogs'),
('de-DE','street_name','Grafen'),('de-DE','street_name','Goethe'),('de-DE','street_name','Schiller'),
('de-DE','street_name','Heine'),('de-DE','street_name','Mozart'),('de-DE','street_name','Bach'),
('de-DE','street_name','Beethoven'),('de-DE','street_name','Handel'),('de-DE','street_name','Schubert'),
('de-DE','street_name','Brahms'),('de-DE','street_name','Haydn'),('de-DE','street_name','Liszt'),
('de-DE','street_name','Kant'),('de-DE','street_name','Hegel'),('de-DE','street_name','Humbold'),
('de-DE','street_name','Scharnhorst'),('de-DE','street_name','Hindenburg'),('de-DE','street_name','Schönfeld'),
('de-DE','street_name','Hochwald'),('de-DE','street_name','Feldweg'),('de-DE','street_name','Amsel'),
('de-DE','street_name','Drossel'),('de-DE','street_name','Finkenburg'),('de-DE','street_name','Lerchen'),
('de-DE','street_name','Schwalben'),('de-DE','street_name','Storch'),('de-DE','street_name','Habicht'),
('de-DE','street_name','Falken'),('de-DE','street_name','Adler'),('de-DE','street_name','Elster'),
('de-DE','street_name','Krähen'),('de-DE','street_name','Schwanen'),('de-DE','street_name','Enten'),
('de-DE','street_name','Fuchs'),('de-DE','street_name','Hasen'),('de-DE','street_name','Rehe'),
('de-DE','street_name','Hirsch'),('de-DE','street_name','Bären'),('de-DE','street_name','Wolves'),
('de-DE','street_name','Neu'),('de-DE','street_name','Alt'),('de-DE','street_name','Ober'),
('de-DE','street_name','Unter'),('de-DE','street_name','Mittel'),('de-DE','street_name','Hinter'),
('de-DE','street_name','Vorder'),('de-DE','street_name','Nieder'),('de-DE','street_name','Ober'),
('de-DE','street_name','Kreuz'),('de-DE','street_name','Sonnen'),('de-DE','street_name','Mond'),
('de-DE','street_name','Stern'),('de-DE','street_name','Wolken'),('de-DE','street_name','Regen'),
('de-DE','street_name','Schnee'),('de-DE','street_name','Eis'),('de-DE','street_name','Frost');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Street suffixes
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','street_suffix','straße'),('de-DE','street_suffix','gasse'),
('de-DE','street_suffix','weg'),('de-DE','street_suffix','allee'),
('de-DE','street_suffix','platz'),('de-DE','street_suffix','ring'),
('de-DE','street_suffix','damm'),('de-DE','street_suffix','stieg'),
('de-DE','street_suffix','pfad'),('de-DE','street_suffix','zeile');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Cities
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','city','{"city":"Berlin","state":"Berlin","zip":"1####"}'),
('de-DE','city','{"city":"Hamburg","state":"Hamburg","zip":"2####"}'),
('de-DE','city','{"city":"München","state":"Bayern","zip":"8####"}'),
('de-DE','city','{"city":"Köln","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Frankfurt am Main","state":"Hessen","zip":"6####"}'),
('de-DE','city','{"city":"Stuttgart","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Düsseldorf","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Leipzig","state":"Sachsen","zip":"04###"}'),
('de-DE','city','{"city":"Dortmund","state":"Nordrhein-Westfalen","zip":"44###"}'),
('de-DE','city','{"city":"Essen","state":"Nordrhein-Westfalen","zip":"45###"}'),
('de-DE','city','{"city":"Bremen","state":"Bremen","zip":"28###"}'),
('de-DE','city','{"city":"Dresden","state":"Sachsen","zip":"01###"}'),
('de-DE','city','{"city":"Hannover","state":"Niedersachsen","zip":"30###"}'),
('de-DE','city','{"city":"Nürnberg","state":"Bayern","zip":"90###"}'),
('de-DE','city','{"city":"Duisburg","state":"Nordrhein-Westfalen","zip":"47###"}'),
('de-DE','city','{"city":"Bochum","state":"Nordrhein-Westfalen","zip":"44###"}'),
('de-DE','city','{"city":"Wuppertal","state":"Nordrhein-Westfalen","zip":"42###"}'),
('de-DE','city','{"city":"Bonn","state":"Nordrhein-Westfalen","zip":"53###"}'),
('de-DE','city','{"city":"Bielefeld","state":"Nordrhein-Westfalen","zip":"33###"}'),
('de-DE','city','{"city":"Münster","state":"Nordrhein-Westfalen","zip":"48###"}'),
('de-DE','city','{"city":"Mannheim","state":"Baden-Württemberg","zip":"68###"}'),
('de-DE','city','{"city":"Karlsruhe","state":"Baden-Württemberg","zip":"76###"}'),
('de-DE','city','{"city":"Augsburg","state":"Bayern","zip":"86###"}'),
('de-DE','city','{"city":"Wiesbaden","state":"Hessen","zip":"65###"}'),
('de-DE','city','{"city":"Gelsenkirchen","state":"Nordrhein-Westfalen","zip":"45###"}'),
('de-DE','city','{"city":"Mönchengladbach","state":"Nordrhein-Westfalen","zip":"41###"}'),
('de-DE','city','{"city":"Braunschweig","state":"Niedersachsen","zip":"38###"}'),
('de-DE','city','{"city":"Chemnitz","state":"Sachsen","zip":"09###"}'),
('de-DE','city','{"city":"Kiel","state":"Schleswig-Holstein","zip":"24###"}'),
('de-DE','city','{"city":"Aachen","state":"Nordrhein-Westfalen","zip":"52###"}'),
('de-DE','city','{"city":"Halle","state":"Sachsen-Anhalt","zip":"06###"}'),
('de-DE','city','{"city":"Magdeburg","state":"Sachsen-Anhalt","zip":"39###"}'),
('de-DE','city','{"city":"Freiburg im Breisgau","state":"Baden-Württemberg","zip":"79###"}'),
('de-DE','city','{"city":"Krefeld","state":"Nordrhein-Westfalen","zip":"47###"}'),
('de-DE','city','{"city":"Lübeck","state":"Schleswig-Holstein","zip":"23###"}'),
('de-DE','city','{"city":"Oberhausen","state":"Nordrhein-Westfalen","zip":"46###"}'),
('de-DE','city','{"city":"Erfurt","state":"Thüringen","zip":"99###"}'),
('de-DE','city','{"city":"Mainz","state":"Rheinland-Pfalz","zip":"55###"}'),
('de-DE','city','{"city":"Rostock","state":"Mecklenburg-Vorpommern","zip":"18###"}'),
('de-DE','city','{"city":"Kassel","state":"Hessen","zip":"34###"}'),
('de-DE','city','{"city":"Hagen","state":"Nordrhein-Westfalen","zip":"58###"}'),
('de-DE','city','{"city":"Saarbrücken","state":"Saarland","zip":"66###"}'),
('de-DE','city','{"city":"Potsdam","state":"Brandenburg","zip":"14###"}'),
('de-DE','city','{"city":"Hamm","state":"Nordrhein-Westfalen","zip":"59###"}'),
('de-DE','city','{"city":"Ludwigshafen","state":"Rheinland-Pfalz","zip":"67###"}'),
('de-DE','city','{"city":"Oldenburg","state":"Niedersachsen","zip":"26###"}'),
('de-DE','city','{"city":"Osnabrück","state":"Niedersachsen","zip":"49###"}'),
('de-DE','city','{"city":"Heidelberg","state":"Baden-Württemberg","zip":"69###"}'),
('de-DE','city','{"city":"Darmstadt","state":"Hessen","zip":"64###"}'),
('de-DE','city','{"city":"Regensburg","state":"Bayern","zip":"93###"}');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Eye colors
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','eye_color','Braun'),('de-DE','eye_color','Blau'),
('de-DE','eye_color','Grün'),('de-DE','eye_color','Haselnuss'),
('de-DE','eye_color','Grau'),('de-DE','eye_color','Bernstein');

-- ────────────────────────────────────────────────────────────
-- Email domains (locale=any)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('any','email_domain','gmail.com'),('any','email_domain','yahoo.com'),
('any','email_domain','hotmail.com'),('any','email_domain','outlook.com'),
('any','email_domain','icloud.com'),('any','email_domain','protonmail.com'),
('any','email_domain','aol.com'),('any','email_domain','live.com'),
('any','email_domain','mail.com'),('any','email_domain','zoho.com'),
('any','email_domain','yandex.com'),('any','email_domain','gmx.de'),
('any','email_domain','web.de'),('any','email_domain','t-online.de'),
('any','email_domain','freenet.de'),('any','email_domain','gmx.net'),
('any','email_domain','comcast.net'),('any','email_domain','verizon.net'),
('any','email_domain','att.net'),('any','email_domain','sbcglobal.net');

-- ============================================================
-- EXPANSION — adds more data to reach 100k–1M user capacity
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- EN-US  Additional first names (male +100)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','first_male','Liam'),('en-US','first_male','Oliver'),('en-US','first_male','Lucas'),
('en-US','first_male','Mason'),('en-US','first_male','Aiden'),('en-US','first_male','Logan'),
('en-US','first_male','Elijah'),('en-US','first_male','Carter'),('en-US','first_male','Owen'),
('en-US','first_male','Sebastian'),('en-US','first_male','Landon'),('en-US','first_male','Julian'),
('en-US','first_male','Caleb'),('en-US','first_male','Levi'),('en-US','first_male','Isaiah'),
('en-US','first_male','Evan'),('en-US','first_male','Connor'),('en-US','first_male','Hunter'),
('en-US','first_male','Leo'),('en-US','first_male','Jayden'),('en-US','first_male','Gavin'),
('en-US','first_male','Cooper'),('en-US','first_male','Isaac'),('en-US','first_male','Wyatt'),
('en-US','first_male','Chase'),('en-US','first_male','Xavier'),('en-US','first_male','Parker'),
('en-US','first_male','Ian'),('en-US','first_male','Tristan'),('en-US','first_male','Blake'),
('en-US','first_male','Colton'),('en-US','first_male','Adrian'),('en-US','first_male','Nathaniel'),
('en-US','first_male','Hudson'),('en-US','first_male','Jaxon'),('en-US','first_male','Dominic'),
('en-US','first_male','Josiah'),('en-US','first_male','Carlos'),('en-US','first_male','Roman'),
('en-US','first_male','Camden'),('en-US','first_male','Maxwell'),('en-US','first_male','Simon'),
('en-US','first_male','Miles'),('en-US','first_male','Sawyer'),('en-US','first_male','Theodore'),
('en-US','first_male','Damian'),('en-US','first_male','Emmett'),('en-US','first_male','Ryder'),
('en-US','first_male','Spencer'),('en-US','first_male','Felix'),('en-US','first_male','Archer'),
('en-US','first_male','Jasper'),('en-US','first_male','Hugo'),('en-US','first_male','Mateo'),
('en-US','first_male','Finn'),('en-US','first_male','Beckett'),('en-US','first_male','Cole'),
('en-US','first_male','Reid'),('en-US','first_male','Brooks'),('en-US','first_male','Tucker'),
('en-US','first_male','Jude'),('en-US','first_male','Silas'),('en-US','first_male','Harrison'),
('en-US','first_male','Easton'),('en-US','first_male','Dean'),('en-US','first_male','Greyson'),
('en-US','first_male','Preston'),('en-US','first_male','Antonio'),('en-US','first_male','Elliott'),
('en-US','first_male','Nolan'),('en-US','first_male','Abel'),('en-US','first_male','Grant'),
('en-US','first_male','Ezekiel'),('en-US','first_male','Bennett'),('en-US','first_male','Rhett'),
('en-US','first_male','Knox'),('en-US','first_male','Axel'),('en-US','first_male','August'),
('en-US','first_male','Jace'),('en-US','first_male','Ezra'),('en-US','first_male','Asher'),
('en-US','first_male','Troy'),('en-US','first_male','Gage'),('en-US','first_male','Seth'),
('en-US','first_male','Lorenzo'),('en-US','first_male','Victor'),('en-US','first_male','Omar'),
('en-US','first_male','Jonah'),('en-US','first_male','Cash'),('en-US','first_male','Paxton'),
('en-US','first_male','Beau'),('en-US','first_male','Rowan'),('en-US','first_male','Zane'),
('en-US','first_male','Rafael'),('en-US','first_male','Milo'),('en-US','first_male','Diego'),
('en-US','first_male','Bryce'),('en-US','first_male','Caden'),('en-US','first_male','Hayden');

-- ────────────────────────────────────────────────────────────
-- EN-US  Additional first names (female +100)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','first_female','Olivia'),('en-US','first_female','Emma'),('en-US','first_female','Ava'),
('en-US','first_female','Charlotte'),('en-US','first_female','Sophia'),('en-US','first_female','Amelia'),
('en-US','first_female','Isabella'),('en-US','first_female','Mia'),('en-US','first_female','Evelyn'),
('en-US','first_female','Harper'),('en-US','first_female','Luna'),('en-US','first_female','Camila'),
('en-US','first_female','Gianna'),('en-US','first_female','Elizabeth'),('en-US','first_female','Eleanor'),
('en-US','first_female','Ella'),('en-US','first_female','Abigail'),('en-US','first_female','Sofia'),
('en-US','first_female','Avery'),('en-US','first_female','Scarlett'),('en-US','first_female','Emily'),
('en-US','first_female','Aria'),('en-US','first_female','Penelope'),('en-US','first_female','Chloe'),
('en-US','first_female','Layla'),('en-US','first_female','Mila'),('en-US','first_female','Nora'),
('en-US','first_female','Hazel'),('en-US','first_female','Madison'),('en-US','first_female','Ellie'),
('en-US','first_female','Lily'),('en-US','first_female','Nova'),('en-US','first_female','Isla'),
('en-US','first_female','Grace'),('en-US','first_female','Violet'),('en-US','first_female','Aurora'),
('en-US','first_female','Riley'),('en-US','first_female','Zoey'),('en-US','first_female','Willow'),
('en-US','first_female','Emilia'),('en-US','first_female','Stella'),('en-US','first_female','Zoe'),
('en-US','first_female','Victoria'),('en-US','first_female','Hannah'),('en-US','first_female','Addison'),
('en-US','first_female','Leah'),('en-US','first_female','Lucy'),('en-US','first_female','Eliana'),
('en-US','first_female','Ivy'),('en-US','first_female','Everly'),('en-US','first_female','Lillian'),
('en-US','first_female','Paisley'),('en-US','first_female','Elena'),('en-US','first_female','Naomi'),
('en-US','first_female','Maya'),('en-US','first_female','Natalie'),('en-US','first_female','Kinsley'),
('en-US','first_female','Delilah'),('en-US','first_female','Claire'),('en-US','first_female','Audrey'),
('en-US','first_female','Aaliyah'),('en-US','first_female','Ruby'),('en-US','first_female','Skylar'),
('en-US','first_female','Savannah'),('en-US','first_female','Anna'),('en-US','first_female','Allison'),
('en-US','first_female','Gabriella'),('en-US','first_female','Kennedy'),('en-US','first_female','Bella'),
('en-US','first_female','Sydney'),('en-US','first_female','Madeline'),('en-US','first_female','Piper'),
('en-US','first_female','Rylee'),('en-US','first_female','Quinn'),('en-US','first_female','Autumn'),
('en-US','first_female','Serenity'),('en-US','first_female','Peyton'),('en-US','first_female','Eva'),
('en-US','first_female','Brianna'),('en-US','first_female','Hailey'),('en-US','first_female','Ariana'),
('en-US','first_female','Kylie'),('en-US','first_female','Jade'),('en-US','first_female','Lydia'),
('en-US','first_female','Morgan'),('en-US','first_female','Alexandra'),('en-US','first_female','Brielle'),
('en-US','first_female','Jade'),('en-US','first_female','Faith'),('en-US','first_female','Hope'),
('en-US','first_female','Juliet'),('en-US','first_female','Valentina'),('en-US','first_female','Nadia'),
('en-US','first_female','Brooke'),('en-US','first_female','Jasmine'),('en-US','first_female','Molly'),
('en-US','first_female','Paige'),('en-US','first_female','Taylor'),('en-US','first_female','Mackenzie');

-- ────────────────────────────────────────────────────────────
-- EN-US  Cities expansion (+150, total ~200)
-- JSON format: {"city":"…","state":"ST","zip":"pattern"}
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('en-US','city','{"city":"Phoenix","state":"AZ","zip":"850##"}'),
('en-US','city','{"city":"Philadelphia","state":"PA","zip":"191##"}'),
('en-US','city','{"city":"San Antonio","state":"TX","zip":"782##"}'),
('en-US','city','{"city":"San Diego","state":"CA","zip":"921##"}'),
('en-US','city','{"city":"Dallas","state":"TX","zip":"752##"}'),
('en-US','city','{"city":"San Jose","state":"CA","zip":"951##"}'),
('en-US','city','{"city":"Austin","state":"TX","zip":"787##"}'),
('en-US','city','{"city":"Jacksonville","state":"FL","zip":"322##"}'),
('en-US','city','{"city":"Fort Worth","state":"TX","zip":"761##"}'),
('en-US','city','{"city":"Columbus","state":"OH","zip":"432##"}'),
('en-US','city','{"city":"San Francisco","state":"CA","zip":"941##"}'),
('en-US','city','{"city":"Charlotte","state":"NC","zip":"282##"}'),
('en-US','city','{"city":"Indianapolis","state":"IN","zip":"462##"}'),
('en-US','city','{"city":"Seattle","state":"WA","zip":"981##"}'),
('en-US','city','{"city":"Denver","state":"CO","zip":"802##"}'),
('en-US','city','{"city":"Boston","state":"MA","zip":"021##"}'),
('en-US','city','{"city":"Nashville","state":"TN","zip":"372##"}'),
('en-US','city','{"city":"Baltimore","state":"MD","zip":"212##"}'),
('en-US','city','{"city":"Louisville","state":"KY","zip":"402##"}'),
('en-US','city','{"city":"Portland","state":"OR","zip":"972##"}'),
('en-US','city','{"city":"Las Vegas","state":"NV","zip":"891##"}'),
('en-US','city','{"city":"Milwaukee","state":"WI","zip":"532##"}'),
('en-US','city','{"city":"Albuquerque","state":"NM","zip":"871##"}'),
('en-US','city','{"city":"Tucson","state":"AZ","zip":"857##"}'),
('en-US','city','{"city":"Fresno","state":"CA","zip":"937##"}'),
('en-US','city','{"city":"Sacramento","state":"CA","zip":"958##"}'),
('en-US','city','{"city":"Mesa","state":"AZ","zip":"852##"}'),
('en-US','city','{"city":"Kansas City","state":"MO","zip":"641##"}'),
('en-US','city','{"city":"Atlanta","state":"GA","zip":"303##"}'),
('en-US','city','{"city":"Omaha","state":"NE","zip":"681##"}'),
('en-US','city','{"city":"Colorado Springs","state":"CO","zip":"809##"}'),
('en-US','city','{"city":"Raleigh","state":"NC","zip":"276##"}'),
('en-US','city','{"city":"Virginia Beach","state":"VA","zip":"234##"}'),
('en-US','city','{"city":"Long Beach","state":"CA","zip":"908##"}'),
('en-US','city','{"city":"Minneapolis","state":"MN","zip":"554##"}'),
('en-US','city','{"city":"Tampa","state":"FL","zip":"336##"}'),
('en-US','city','{"city":"New Orleans","state":"LA","zip":"701##"}'),
('en-US','city','{"city":"Arlington","state":"TX","zip":"760##"}'),
('en-US','city','{"city":"Bakersfield","state":"CA","zip":"933##"}'),
('en-US','city','{"city":"Honolulu","state":"HI","zip":"968##"}'),
('en-US','city','{"city":"Anaheim","state":"CA","zip":"928##"}'),
('en-US','city','{"city":"Aurora","state":"CO","zip":"800##"}'),
('en-US','city','{"city":"Santa Ana","state":"CA","zip":"927##"}'),
('en-US','city','{"city":"Corpus Christi","state":"TX","zip":"784##"}'),
('en-US','city','{"city":"Riverside","state":"CA","zip":"925##"}'),
('en-US','city','{"city":"St. Louis","state":"MO","zip":"631##"}'),
('en-US','city','{"city":"Lexington","state":"KY","zip":"405##"}'),
('en-US','city','{"city":"Pittsburgh","state":"PA","zip":"152##"}'),
('en-US','city','{"city":"Anchorage","state":"AK","zip":"995##"}'),
('en-US','city','{"city":"Stockton","state":"CA","zip":"952##"}'),
('en-US','city','{"city":"Cincinnati","state":"OH","zip":"452##"}'),
('en-US','city','{"city":"St. Paul","state":"MN","zip":"551##"}'),
('en-US','city','{"city":"Toledo","state":"OH","zip":"436##"}'),
('en-US','city','{"city":"Greensboro","state":"NC","zip":"274##"}'),
('en-US','city','{"city":"Newark","state":"NJ","zip":"071##"}'),
('en-US','city','{"city":"Plano","state":"TX","zip":"750##"}'),
('en-US','city','{"city":"Henderson","state":"NV","zip":"890##"}'),
('en-US','city','{"city":"Lincoln","state":"NE","zip":"685##"}'),
('en-US','city','{"city":"Buffalo","state":"NY","zip":"142##"}'),
('en-US','city','{"city":"Fort Wayne","state":"IN","zip":"468##"}'),
('en-US','city','{"city":"Jersey City","state":"NJ","zip":"073##"}'),
('en-US','city','{"city":"Chandler","state":"AZ","zip":"852##"}'),
('en-US','city','{"city":"St. Petersburg","state":"FL","zip":"337##"}'),
('en-US','city','{"city":"Laredo","state":"TX","zip":"780##"}'),
('en-US','city','{"city":"Norfolk","state":"VA","zip":"235##"}'),
('en-US','city','{"city":"Madison","state":"WI","zip":"537##"}'),
('en-US','city','{"city":"Durham","state":"NC","zip":"277##"}'),
('en-US','city','{"city":"Lubbock","state":"TX","zip":"794##"}'),
('en-US','city','{"city":"Winston-Salem","state":"NC","zip":"271##"}'),
('en-US','city','{"city":"Garland","state":"TX","zip":"750##"}'),
('en-US','city','{"city":"Glendale","state":"AZ","zip":"853##"}'),
('en-US','city','{"city":"Hialeah","state":"FL","zip":"330##"}'),
('en-US','city','{"city":"Reno","state":"NV","zip":"895##"}'),
('en-US','city','{"city":"Baton Rouge","state":"LA","zip":"708##"}'),
('en-US','city','{"city":"Irvine","state":"CA","zip":"926##"}'),
('en-US','city','{"city":"Chesapeake","state":"VA","zip":"233##"}'),
('en-US','city','{"city":"Irving","state":"TX","zip":"750##"}'),
('en-US','city','{"city":"Scottsdale","state":"AZ","zip":"852##"}'),
('en-US','city','{"city":"North Las Vegas","state":"NV","zip":"890##"}'),
('en-US','city','{"city":"Fremont","state":"CA","zip":"945##"}'),
('en-US','city','{"city":"Gilbert","state":"AZ","zip":"852##"}'),
('en-US','city','{"city":"San Bernardino","state":"CA","zip":"924##"}'),
('en-US','city','{"city":"Birmingham","state":"AL","zip":"352##"}'),
('en-US','city','{"city":"Rochester","state":"NY","zip":"146##"}'),
('en-US','city','{"city":"Richmond","state":"VA","zip":"232##"}'),
('en-US','city','{"city":"Spokane","state":"WA","zip":"992##"}'),
('en-US','city','{"city":"Des Moines","state":"IA","zip":"503##"}'),
('en-US','city','{"city":"Montgomery","state":"AL","zip":"361##"}'),
('en-US','city','{"city":"Modesto","state":"CA","zip":"953##"}'),
('en-US','city','{"city":"Fayetteville","state":"NC","zip":"283##"}'),
('en-US','city','{"city":"Tacoma","state":"WA","zip":"984##"}'),
('en-US','city','{"city":"Shreveport","state":"LA","zip":"711##"}'),
('en-US','city','{"city":"Fontana","state":"CA","zip":"923##"}'),
('en-US','city','{"city":"Moreno Valley","state":"CA","zip":"925##"}'),
('en-US','city','{"city":"Glendale","state":"CA","zip":"912##"}'),
('en-US','city','{"city":"Akron","state":"OH","zip":"443##"}'),
('en-US','city','{"city":"Huntington Beach","state":"CA","zip":"926##"}'),
('en-US','city','{"city":"Little Rock","state":"AR","zip":"722##"}'),
('en-US','city','{"city":"Columbus","state":"GA","zip":"319##"}'),
('en-US','city','{"city":"Grand Rapids","state":"MI","zip":"495##"}'),
('en-US','city','{"city":"Salt Lake City","state":"UT","zip":"841##"}'),
('en-US','city','{"city":"Tallahassee","state":"FL","zip":"323##"}'),
('en-US','city','{"city":"Huntsville","state":"AL","zip":"358##"}'),
('en-US','city','{"city":"Worcester","state":"MA","zip":"016##"}'),
('en-US','city','{"city":"Knoxville","state":"TN","zip":"379##"}'),
('en-US','city','{"city":"Providence","state":"RI","zip":"029##"}'),
('en-US','city','{"city":"Brownsville","state":"TX","zip":"785##"}'),
('en-US','city','{"city":"Santa Clarita","state":"CA","zip":"913##"}'),
('en-US','city','{"city":"Garden Grove","state":"CA","zip":"928##"}'),
('en-US','city','{"city":"Oceanside","state":"CA","zip":"920##"}'),
('en-US','city','{"city":"Fort Lauderdale","state":"FL","zip":"333##"}'),
('en-US','city','{"city":"Rancho Cucamonga","state":"CA","zip":"917##"}'),
('en-US','city','{"city":"Santa Rosa","state":"CA","zip":"954##"}'),
('en-US','city','{"city":"Ontario","state":"CA","zip":"917##"}'),
('en-US','city','{"city":"Vancouver","state":"WA","zip":"986##"}'),
('en-US','city','{"city":"Tempe","state":"AZ","zip":"852##"}'),
('en-US','city','{"city":"Cape Coral","state":"FL","zip":"339##"}'),
('en-US','city','{"city":"Sioux Falls","state":"SD","zip":"571##"}'),
('en-US','city','{"city":"Peoria","state":"IL","zip":"616##"}'),
('en-US','city','{"city":"Springfield","state":"IL","zip":"627##"}'),
('en-US','city','{"city":"Chattanooga","state":"TN","zip":"374##"}'),
('en-US','city','{"city":"Eugene","state":"OR","zip":"974##"}'),
('en-US','city','{"city":"Fort Collins","state":"CO","zip":"805##"}'),
('en-US','city','{"city":"Jackson","state":"MS","zip":"392##"}'),
('en-US','city','{"city":"Savannah","state":"GA","zip":"314##"}'),
('en-US','city','{"city":"Hayward","state":"CA","zip":"945##"}'),
('en-US','city','{"city":"Paterson","state":"NJ","zip":"075##"}'),
('en-US','city','{"city":"Bridgeport","state":"CT","zip":"066##"}'),
('en-US','city','{"city":"Syracuse","state":"NY","zip":"132##"}'),
('en-US','city','{"city":"Torrance","state":"CA","zip":"905##"}'),
('en-US','city','{"city":"Sunnyvale","state":"CA","zip":"940##"}'),
('en-US','city','{"city":"Escondido","state":"CA","zip":"920##"}'),
('en-US','city','{"city":"Pomona","state":"CA","zip":"917##"}'),
('en-US','city','{"city":"Pasadena","state":"TX","zip":"775##"}'),
('en-US','city','{"city":"Macon","state":"GA","zip":"312##"}'),
('en-US','city','{"city":"Lakewood","state":"CO","zip":"802##"}'),
('en-US','city','{"city":"Killeen","state":"TX","zip":"765##"}'),
('en-US','city','{"city":"Surprise","state":"AZ","zip":"853##"}'),
('en-US','city','{"city":"Roseville","state":"CA","zip":"956##"}'),
('en-US','city','{"city":"Denton","state":"TX","zip":"762##"}'),
('en-US','city','{"city":"Lancaster","state":"CA","zip":"935##"}'),
('en-US','city','{"city":"Palmdale","state":"CA","zip":"934##"}');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Additional first names (male +50)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','first_male','Lukas'),('de-DE','first_male','Finn'),('de-DE','first_male','Emil'),
('de-DE','first_male','Leon'),('de-DE','first_male','Noah'),('de-DE','first_male','Elias'),
('de-DE','first_male','Ben'),('de-DE','first_male','Luca'),('de-DE','first_male','Jonas'),
('de-DE','first_male','Felix'),('de-DE','first_male','Paul'),('de-DE','first_male','Maximilian'),
('de-DE','first_male','Moritz'),('de-DE','first_male','Niklas'),('de-DE','first_male','Philipp'),
('de-DE','first_male','Jan'),('de-DE','first_male','Tobias'),('de-DE','first_male','Simon'),
('de-DE','first_male','Fabian'),('de-DE','first_male','Dominik'),('de-DE','first_male','Florian'),
('de-DE','first_male','Matthias'),('de-DE','first_male','Stefan'),('de-DE','first_male','Ralf'),
('de-DE','first_male','Uwe'),('de-DE','first_male','Bernd'),('de-DE','first_male','Jochen'),
('de-DE','first_male','Dieter'),('de-DE','first_male','Werner'),('de-DE','first_male','Gerhard'),
('de-DE','first_male','Helmut'),('de-DE','first_male','Erich'),('de-DE','first_male','Kurt'),
('de-DE','first_male','Horst'),('de-DE','first_male','Günter'),('de-DE','first_male','Friedrich'),
('de-DE','first_male','Karl'),('de-DE','first_male','Otto'),('de-DE','first_male','Rudolf'),
('de-DE','first_male','Herbert'),('de-DE','first_male','Harald'),('de-DE','first_male','Heinz'),
('de-DE','first_male','Walter'),('de-DE','first_male','Manfred'),('de-DE','first_male','Franz'),
('de-DE','first_male','Benedikt'),('de-DE','first_male','Valentin'),('de-DE','first_male','Oskar'),
('de-DE','first_male','Til'),('de-DE','first_male','Levin');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Additional first names (female +50)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','first_female','Emma'),('de-DE','first_female','Mia'),('de-DE','first_female','Emilia'),
('de-DE','first_female','Sophia'),('de-DE','first_female','Lena'),('de-DE','first_female','Hannah'),
('de-DE','first_female','Lea'),('de-DE','first_female','Mila'),('de-DE','first_female','Lara'),
('de-DE','first_female','Amelie'),('de-DE','first_female','Klara'),('de-DE','first_female','Ida'),
('de-DE','first_female','Johanna'),('de-DE','first_female','Luisa'),('de-DE','first_female','Leonie'),
('de-DE','first_female','Nora'),('de-DE','first_female','Elena'),('de-DE','first_female','Franziska'),
('de-DE','first_female','Carina'),('de-DE','first_female','Vanessa'),('de-DE','first_female','Stefanie'),
('de-DE','first_female','Sabine'),('de-DE','first_female','Petra'),('de-DE','first_female','Brigitte'),
('de-DE','first_female','Helga'),('de-DE','first_female','Ingrid'),('de-DE','first_female','Renate'),
('de-DE','first_female','Gisela'),('de-DE','first_female','Christa'),('de-DE','first_female','Ute'),
('de-DE','first_female','Monika'),('de-DE','first_female','Hannelore'),('de-DE','first_female','Hildegard'),
('de-DE','first_female','Gertrude'),('de-DE','first_female','Waltraud'),('de-DE','first_female','Ilse'),
('de-DE','first_female','Hilde'),('de-DE','first_female','Margarete'),('de-DE','first_female','Elisabeth'),
('de-DE','first_female','Charlotte'),('de-DE','first_female','Frieda'),('de-DE','first_female','Berta'),
('de-DE','first_female','Paula'),('de-DE','first_female','Theresa'),('de-DE','first_female','Veronika'),
('de-DE','first_female','Antonia'),('de-DE','first_female','Valentina'),('de-DE','first_female','Sina'),
('de-DE','first_female','Jette'),('de-DE','first_female','Marlene');

-- ────────────────────────────────────────────────────────────
-- DE-DE  Cities expansion (+100, total ~150)
-- ────────────────────────────────────────────────────────────
INSERT INTO fake.lookup (locale, category, value) VALUES
('de-DE','city','{"city":"Berlin","state":"Berlin","zip":"1####"}'),
('de-DE','city','{"city":"München","state":"Bayern","zip":"8####"}'),
('de-DE','city','{"city":"Hamburg","state":"Hamburg","zip":"2####"}'),
('de-DE','city','{"city":"Köln","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Frankfurt am Main","state":"Hessen","zip":"6####"}'),
('de-DE','city','{"city":"Stuttgart","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Düsseldorf","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Leipzig","state":"Sachsen","zip":"0####"}'),
('de-DE','city','{"city":"Dortmund","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Essen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Bremen","state":"Bremen","zip":"2####"}'),
('de-DE','city','{"city":"Dresden","state":"Sachsen","zip":"0####"}'),
('de-DE','city','{"city":"Hannover","state":"Niedersachsen","zip":"3####"}'),
('de-DE','city','{"city":"Nürnberg","state":"Bayern","zip":"9####"}'),
('de-DE','city','{"city":"Duisburg","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Bochum","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Wuppertal","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Bielefeld","state":"Nordrhein-Westfalen","zip":"3####"}'),
('de-DE','city','{"city":"Bonn","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Münster","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Mannheim","state":"Baden-Württemberg","zip":"6####"}'),
('de-DE','city','{"city":"Karlsruhe","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Augsburg","state":"Bayern","zip":"8####"}'),
('de-DE','city','{"city":"Wiesbaden","state":"Hessen","zip":"6####"}'),
('de-DE','city','{"city":"Gelsenkirchen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Mönchengladbach","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Braunschweig","state":"Niedersachsen","zip":"3####"}'),
('de-DE','city','{"city":"Chemnitz","state":"Sachsen","zip":"0####"}'),
('de-DE','city','{"city":"Kiel","state":"Schleswig-Holstein","zip":"2####"}'),
('de-DE','city','{"city":"Aachen","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Halle","state":"Sachsen-Anhalt","zip":"0####"}'),
('de-DE','city','{"city":"Magdeburg","state":"Sachsen-Anhalt","zip":"3####"}'),
('de-DE','city','{"city":"Freiburg im Breisgau","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Krefeld","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Mainz","state":"Rheinland-Pfalz","zip":"5####"}'),
('de-DE','city','{"city":"Lübeck","state":"Schleswig-Holstein","zip":"2####"}'),
('de-DE','city','{"city":"Erfurt","state":"Thüringen","zip":"9####"}'),
('de-DE','city','{"city":"Oberhausen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Rostock","state":"Mecklenburg-Vorpommern","zip":"1####"}'),
('de-DE','city','{"city":"Kassel","state":"Hessen","zip":"3####"}'),
('de-DE','city','{"city":"Hagen","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Hamm","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Saarbrücken","state":"Saarland","zip":"6####"}'),
('de-DE','city','{"city":"Mülheim an der Ruhr","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Potsdam","state":"Brandenburg","zip":"1####"}'),
('de-DE','city','{"city":"Osnabrück","state":"Niedersachsen","zip":"4####"}'),
('de-DE','city','{"city":"Ludwigshafen","state":"Rheinland-Pfalz","zip":"6####"}'),
('de-DE','city','{"city":"Oldenburg","state":"Niedersachsen","zip":"2####"}'),
('de-DE','city','{"city":"Leverkusen","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Heidelberg","state":"Baden-Württemberg","zip":"6####"}'),
('de-DE','city','{"city":"Darmstadt","state":"Hessen","zip":"6####"}'),
('de-DE','city','{"city":"Paderborn","state":"Nordrhein-Westfalen","zip":"3####"}'),
('de-DE','city','{"city":"Würzburg","state":"Bayern","zip":"9####"}'),
('de-DE','city','{"city":"Regensburg","state":"Bayern","zip":"9####"}'),
('de-DE','city','{"city":"Ingolstadt","state":"Bayern","zip":"8####"}'),
('de-DE','city','{"city":"Göttingen","state":"Niedersachsen","zip":"3####"}'),
('de-DE','city','{"city":"Wolfsburg","state":"Niedersachsen","zip":"3####"}'),
('de-DE','city','{"city":"Offenbach am Main","state":"Hessen","zip":"6####"}'),
('de-DE','city','{"city":"Ulm","state":"Baden-Württemberg","zip":"8####"}'),
('de-DE','city','{"city":"Bottrop","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Recklinghausen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Bremerhaven","state":"Bremen","zip":"2####"}'),
('de-DE','city','{"city":"Fürth","state":"Bayern","zip":"9####"}'),
('de-DE','city','{"city":"Remscheid","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Solingen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Heilbronn","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Pforzheim","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Neuss","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Erfurt","state":"Thüringen","zip":"9####"}'),
('de-DE','city','{"city":"Gera","state":"Thüringen","zip":"0####"}'),
('de-DE','city','{"city":"Koblenz","state":"Rheinland-Pfalz","zip":"5####"}'),
('de-DE','city','{"city":"Jena","state":"Thüringen","zip":"0####"}'),
('de-DE','city','{"city":"Trier","state":"Rheinland-Pfalz","zip":"5####"}'),
('de-DE','city','{"city":"Erlangen","state":"Bayern","zip":"9####"}'),
('de-DE','city','{"city":"Moers","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Siegen","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Hildesheim","state":"Niedersachsen","zip":"3####"}'),
('de-DE','city','{"city":"Salzgitter","state":"Niedersachsen","zip":"3####"}'),
('de-DE','city','{"city":"Cottbus","state":"Brandenburg","zip":"0####"}'),
('de-DE','city','{"city":"Kaiserslautern","state":"Rheinland-Pfalz","zip":"6####"}'),
('de-DE','city','{"city":"Herne","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Gütersloh","state":"Nordrhein-Westfalen","zip":"3####"}'),
('de-DE','city','{"city":"Iserlohn","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Schwerin","state":"Mecklenburg-Vorpommern","zip":"1####"}'),
('de-DE','city','{"city":"Witten","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Düren","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Ratingen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Zwickau","state":"Sachsen","zip":"0####"}'),
('de-DE','city','{"city":"Marl","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Tübingen","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Villingen-Schwenningen","state":"Baden-Württemberg","zip":"7####"}'),
('de-DE','city','{"city":"Bergisch Gladbach","state":"Nordrhein-Westfalen","zip":"5####"}'),
('de-DE','city','{"city":"Minden","state":"Nordrhein-Westfalen","zip":"3####"}'),
('de-DE','city','{"city":"Velbert","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Lünen","state":"Nordrhein-Westfalen","zip":"4####"}'),
('de-DE','city','{"city":"Dessau-Roßlau","state":"Sachsen-Anhalt","zip":"0####"}'),
('de-DE','city','{"city":"Erlangen","state":"Bayern","zip":"9####"}');

-- ────────────────────────────────────────────────────────────
-- Additional email domains (locale=any)
-- ────────────────────────────────────_____________________
INSERT INTO fake.lookup (locale, category, value) VALUES
('any','email_domain','fastmail.com'),('any','email_domain','tutanota.com'),
('any','email_domain','hey.com'),('any','email_domain','pm.me'),
('any','email_domain','duck.com'),('any','email_domain','mailbox.org'),
('any','email_domain','runbox.com'),('any','email_domain','posteo.de'),
('any','email_domain','disroot.org'),('any','email_domain','msn.com');
